### ISSUE TITLE
action potential terms should be obsoleted

### ISSUE THREAD

**Issue by dosumis** [obophenotype/bio-attribute-ontology#1]
OBA action potential terms are incorrect.  Action potential was originally treated as a quality in GO - probably becuase of a false analogy with membrane potential.  It is now modelled as a process that regulates membrane potential.  The result is that there are a set of terms in OBA whose names are duplicates of GO action potential terms.  These OBA: terms should be obsoleted:

The terms action potential (OBA:0000012) and action potential (GO:0001508) share the name or synonym "action potential".
  The terms atrial cardiac muscle cell action potential (GO:0086014) and atrial cardiac muscle cell action potential (OBA:0000019) share the name or synonym "atrial cardiac muscle cell action potential".
  The terms AV node cardiac muscle cell action potential (OBA:0000002) and AV node cell action potential (GO:0086016) share the name or synonym "AV node cardiac muscle cell action potential".
AV node cell action potential (GO:0086016) generated 1 warning:
  The terms bundle of His cell action potential (GO:0086043) and bundle of His cardiac muscle cell action potential (OBA:0000038) share the name or synonym "bundle of His cardiac muscle cell action potential".
  The terms cardiac muscle cell action potential (OBA:0000044) and cardiac muscle cell action potential (GO:0086001) share the name or synonym "cardiac muscle cell action potential".

**Comment by cmungall** [comment]
Yep, they're already obsolete in oba-edit (as you surmised the original oba was in part reverse enginered from a much earlier go). Will make a new release

**Comment by cmungall** [comment]
Was in the release. Looks like a go pipeline issue...
