### ISSUE TITLE
NTR: cytosolic calcium ion concentration + pre & post-synaptic cytosol calcium ion concentration

### ISSUE THREAD

**Issue by dosumis** [obophenotype/bio-attribute-ontology#10]
3 new terms needed for synapse project see geneontology/synapse#43, geneontology/synapse#46.

**Comment by cmungall** [comment]
This was added in response to a GO request: [OBA:0000040](http://purl.obolibrary.org/obo/OBA_0000040) ! calcium ion concentration

Will add post-synaptic

**Comment by cmungall** [comment]
EDIT: this one: [OBA:0006038](http://purl.obolibrary.org/obo/OBA_0006038) ! concentration of of calcium ion in cytosol
