### ISSUE TITLE
First steps for EFO/VT alignment

### ISSUE THREAD

**Issue by matentzn** [obophenotype/bio-attribute-ontology#101]
- [x] Add all the missed OBA-VT mappings into the Google sheet (randomly review 5 of them only)
- [x] Add all the unreviewed OBA-EFO SSSOM mappings to the Google sheet
- [x] Add all the unreviewed OBA-VT SSSOM mappings to the Google sheet
- [ ] Move all the response to mappings and other mappings from the other sheets in the Google sheet into the  OBA-EFO SSSOM
- [ ] Run make "sync_sssom_google_sheets" (or something like that, see [here](https://obophenotype.github.io/bio-attribute-ontology/editors-guide/))
- [ ] Make PR and assign me

**Comment by dosumis** [comment]
@matentzn - some possible tweaks from discussion in GWAS call this week. 

* We think it might be better to match Entity first, and then quality as occasionally Q names can be embedded in E labels/synonyms, e.g. PATO term 'immature' matches part of the CL term 'immature basophil'

* Entity matches are also needed for CHEBI and Proteins.  For GWAS catalog purposes, matching to PRO human terms  might be best, but thinking about it, perhaps we should keep more generic.  (For downstream use, we should look in to how easy it is to map from PRO to uniprot human).

**Comment by matentzn** [comment]
Ok, this should not be too hard to do - will do it during the next OBA call - until then there should still be plenty of alignment suggestions to be curated in!

**Comment by matentzn** [comment]
We will close this issue now in favour of more specialised issues in the future
