### ISSUE TITLE
snout length definition

### ISSUE THREAD

**Issue by megbalk** [obophenotype/bio-attribute-ontology#113]
## Synonyms
muzzle length (?); @matentzn muzzle is a synonym of snout so would a search for muzzle length pull up snout length?

## Textual definition

Expand definition to include: Typically measured on the ventral side of a skull along the anterior-posterior axis from the anterior part of the I1 (prosthion) to the anterior side of P2 on either the right or left side of a skull.

## Attribution
https://orcid.org/0000-0003-2699-3066
@helenamachado https://orcid.org/0000-0001-8415-4848

**Comment by megbalk** [comment]
This can be an rdfs:comment (see issue #137)

**Comment by matentzn** [comment]
> muzzle is a synonym of snout so would a search for muzzle length pull up snout length

This is a good question, this makes sense but would require a new feature in dosdp tools:

https://github.com/INCATools/dosdp-tools/issues/246

**Comment by megbalk** [comment]
I'm not sure I follow that issue

Would it be worth making an annotation property like "other measurement label"?

**Comment by matentzn** [comment]
This issue basically means:

If a phenotype P refers to an anatomical entity A, and A has a synonym S, then we would want P to have a synonym based on the synonym of A! 

> Would it be worth making an annotation property like "other measurement label"?

Why, is synonym not good enough?

**Comment by megbalk** [comment]
oh synonym is good enough! I wasn't sure if it did work like that or not. Here, 'snout' has synonym 'muzzle', but 'snout length' does not have synonym 'muzzle length'. So, because 'snout' has a synonym 'muzzle', if someone searched 'muzzle length', would 'snout length' show up?

I will make another issue about "other measurement label" as to not confuse this thread.

**Comment by matentzn** [comment]
Yes, I think it should - but for that to really happen (right now it does not) we need to show some enthusiasm here: https://github.com/INCATools/dosdp-tools/issues/246 :)

**Comment by megbalk** [comment]
For now, I'll manually make a synonym.
