### ISSUE TITLE
New OBA release

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#118]
Depends on
- [x] https://github.com/obophenotype/bio-attribute-ontology/issues/111

Required by
- https://github.com/EBISPOT/efo/issues/1693
- https://github.com/EBISPOT/efo/issues/1658

**Comment by rays22** [comment]
I ran into some errors caused by obsolete GO biological process classes.

1. ERROR   misused_obsolete_label  OBA:0004273     rdfs:label      obsolete cell aging onset quality <-- [GO:0007569 obsolete cell aging](https://www.ebi.ac.uk/QuickGO/term/GO:0007569)
```
../patterns/data/default/entity_attribute.tsv
4576:OBA:0004273                GO:0007569      cell aging      PATO:0002325    onset quality
```
I can fix this by using `GO:0090398	Biological Process	cellular senescence`.

2. ERROR   misused_obsolete_label  OBA:1000815     rdfs:label      obsolete subarachnoid space development quality
<-- [GO:1903374 obsolete subarachnoid space development](https://www.ebi.ac.uk/QuickGO/term/GO:1903374)
```
../patterns/data/default/entity_attribute.tsv
7003:OBA:1000815                GO:1903374      subarachnoid space development  PATO:0000001    quality
```
@matentzn , what to do with this one?

**Comment by matentzn** [comment]
If the term has been obsoleted you will have to replace it with a pattern (assuming that sub arch. Space is an Uberon term). No replacement?

**Comment by rays22** [comment]
> If the term has been obsoleted without replacement you will have to replace it with a pattern (assuming that sub arch. Space is an Uberon term). No replacement?

Yes it is UBERON:0000315 subarachnoid space. There is no replacement for GO:1903374      subarachnoid space development.

**Comment by rays22** [comment]
`oba-full.owl` and `oba.owl` have grown too big and I can not push them to github. I get errors:

>remote: error: See http://git.io/iEPt8g for more information.
remote: error: File oba-full.owl is 108.99 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File oba.owl is 108.64 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To github.com:obophenotype/bio-attribute-ontology.git
 ! [remote rejected] release-2022-08-02 -> release-2022-08-02 (pre-receive hook declined)
error: failed to push some refs to 'github.com:obophenotype/bio-attribute-ontology.git'

@matentzn, do you think it is because the chebi and pr imports are huge?

**Comment by matentzn** [comment]
Yeah we will need to move to a different release system. I can do it but you have to send me a list of file names that have changed since the last successful commit to GitHub. Is this just a single commit?

**Comment by rays22** [comment]
Yes, just a singe commit.
The list of files with changes in the last commit that has failed the push:

```
git diff HEAD~1 --name-only
oba-base.json
oba-base.obo
oba-base.owl
oba-basic.json
oba-basic.obo
oba-basic.owl
oba-full.json
oba-full.obo
oba-full.owl
oba.json
oba.obo
oba.owl
patterns/definitions.owl
patterns/pattern.owl
src/ontology/imports/chebi_import.owl
src/ontology/imports/cl_import.owl
src/ontology/imports/go_import.owl
src/ontology/imports/hp_import.owl
src/ontology/imports/mondo_import.owl
src/ontology/imports/nbo_import.owl
src/ontology/imports/omo_import.owl
src/ontology/imports/pato_import.owl
src/ontology/imports/po_import.owl
src/ontology/imports/pr_import.owl
src/ontology/imports/ro_import.owl
src/ontology/imports/so_import.owl
src/ontology/imports/uberon_import.owl
src/patterns/definitions.owl
src/patterns/pattern.owl
```

**Comment by rays22** [comment]
#### These are the large files (>50MB):
1. oba.json	62.42 MB
2. oba-full.json is	62.42 MB
3. oba-full.owl	108.99 MB
4. oba.owl	108.64 MB

@matentzn ,
Shall I [remove them from the last commit](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#removing-files-from-a-repositorys-history) and push the rest?

**Comment by matentzn** [comment]
No, we need to do a different workflow:

1. Remove them from the last commit
1. git rm the following files:
    ```
    oba-basic.{owl,json,obo}
    oba-base.{json,obo}
    oba-full.{owl,json,obo}
    oba.{json,owl}
    ```
1. Add them all to .gitignore (Note that oba-base.owl and oba.obo are not removed, and not added to .gitignore)
1. Merge this PR
1. Make a release as usual
1. Attach all (!) release files (including oba-base.owl and oba.obo) to the github release as "binaries" (we have been doing that anyways)

Let me know how it goes!
