### ISSUE TITLE
other measurement label

### ISSUE THREAD

**Issue by megbalk** [obophenotype/bio-attribute-ontology#152]
The thought behind having other measurement label is to allow people using ambiguous terms to search the ontology.

Two examples are:

'viscerocranium length' as an alternative label for 'facial skeleton length'. This doesn't suggest they are synonyms (see discussion on facial skeleton [here](https://github.com/obophenotype/uberon/issues/2630)).

or 'skull length' as an alternative label for 'ventral cranium length'. Our measurement standards call the measurement along the ventral side of a cranium 'skull length', but in UBERON 'skull' includes the mandible, while the measurement excludes the mandible. This way we're not making synonyms and confusing the relationships.

**Comment by matentzn** [comment]
Hmm... that is what `oboInOwl:hasRelatedSynonym` is for.. I think. Chris would not like to curate these kinds of synonyms.. I think for him synonyms are alternative labels used to refer to the _same_ concept. But the difference is so hazy in practice. Lets curate them now as `oboInOwl:hasRelatedSynonym` and if people complain later, we rethink our strategy. A new property is just going to be ignored by most users..
