### ISSUE TITLE
total skin mass

### ISSUE THREAD

**Issue by megbalk** [obophenotype/bio-attribute-ontology#159]
For new term requests, please provide the following information:

## Preferred term label

total skin mass

## Textual definition

The total mass of the skin. This is different from "skin mass", which is only the mass of a zone of skin.

## Suggested parent term

body size trait

## Attribution

https://orcid.org/0000-0003-2699-3066

**Comment by megbalk** [comment]
@rays22 I'm having trouble making changes

**Comment by rays22** [comment]
> @rays22 I'm having trouble making changes

What changes are you trying to make and specifically where?

**Comment by megbalk** [comment]
I added a line to "entity_attribute.tsv" (using tabs rather than ",")
OBA:203004, total skin mass, UBERON:0002097, skin of body, PATO:0000125, mass

It would not let me save the tsv but would have me create a new document

**Comment by megbalk** [comment]
@rays22 I think I got it to work!
