### ISSUE TITLE
Map NCIT measurements

### ISSUE THREAD

**Issue by cmungall** [obophenotype/bio-attribute-ontology#163]
Examples

NCIT:C51948 ! Leukocyte Count
NCIT:C51949 ! Lymphocyte Count
NCIT:C51950 ! Neutrophil Count
NCIT:C51951 ! Platelet Count
NCIT:C61015 ! Serum Albumin Measurement
NCIT:C61016 ! Serum Alkaline Phosphatase Measurement
NCIT:C61017 ! Serum Alanine Aminotransferase Measurement
NCIT:C61018 ! Serum Aspartate Aminotransferase Measurement
NCIT:C61019 ! Blood Urea Nitrogen Measurement
NCIT:C61023 ! Serum Creatinine Measurement
NCIT:C61027 ! Serum Glucose Measurement
NCIT:C61029 ! Serum Sodium Measurement
NCIT:C61031 ! Serum Total Bilirubin Measurement
NCIT:C61033 ! Serum Total Protein Measurement
NCIT:C61037 ! Serum Triglyceride Measurement
NCIT:C61041 ! Serum HDL Cholesterol Measurement
NCIT:C61042 ! Serum LDL Cholesterol Measurement
NCIT:C64433 ! Alanine Aminotransferase Measurement
NCIT:C64467 ! Aspartate Aminotransferase Measurement
NCIT:C64470 ! Total Basophil Count
NCIT:C64471 ! Basophil to Leukocyte Ratio
NCIT:C64488 ! Calcium Measurement
NCIT:C64495 ! Chloride Measurement
NCIT:C64545 ! Carbon Dioxide Measurement
NCIT:C64547 ! Creatinine Measurement
NCIT:C64550 ! Eosinophil Count
NCIT:C64604 ! Eosinophil to Leukocyte Ratio
NCIT:C64796 ! Hematocrit Measurement
NCIT:C64810 ! Nitrite Measurement
NCIT:C64816 ! Urobilinogen Measurement

Note: as stated a few other places I don't think we should separate characteristics from measurements, it's the same concept

I believe this would be of value to cpath cc @nicolevasilevsky

**Comment by matentzn** [comment]
I agree these would be extremely useful for OBA.

**Comment by ramonawalls** [comment]
Just to make sure I understand, OBA does not include classes for measurements, right, an these would map (somehow) to the relevant quality that is being measured?

**Comment by matentzn** [comment]
@ramonawalls - while there is clearly a conceptual difference between "Total Basophil Count" **_measurement_** (an observation which has, for example, an observer), and "total basophil count"  **_trait_**  (an observable characteristic of an organism) we do not believe that having classes for both make any sense. It will take years to bridge "information" and "characteristic"-centric data models as they have proliferated widely, but it is our belief that only the "characteristic" itself should be represented as a named class (the "measurement" aspect of a characteristic is purely a "shadow" of the actual characteristic), and that the occurrence of either one (measurement or trait) should be, for most biomedical data integration use cases, "conflated" (i.e. you should pretend they are the same). So in this case here (as with our EFO alignment) we will create all of these as trait terms, but pretend, that they relate to the same thing (i.e yes, map across).

**Comment by ramonawalls** [comment]
Thanks, @matentzn . I agree completely that there should not be parallel hierarchies of traits and measurement types. Saying that there is "a conceptual difference" between the two types understates the importance of the difference, at least for the kind of work I have done, but I support the conflation approach for knowledge graph work. I just wanted to be sure that in OBA, qualities are logically defined as qualities, not processes or information, so that if we want to use more robust reasoning, we can.

C-Path should be able to commit some resources to the mapping, if you can let us know what needs to be done.

**Comment by matentzn** [comment]
> I just wanted to be sure that in OBA, qualities are logically defined as qualities, not processes or information, so that if we want to use more robust reasoning, we can.

100%! This is what they are. 

@rays22 hold of on this for a moment.

@ramonawalls basically what we need is simply a two column table for each of these NCIT terms, the first column being the appropriate PATO quality and the second the respective entity, i.e. Hematocrit etc. This is not always trivial, but I think its not too bad.

The ratio ones require a new pattern I think. @rays22 can you propose a simple logical pattern for capturing the ratio traits? It should be aligned with uPheno.
