### ISSUE TITLE
PURL not resolvable

### ISSUE THREAD

**Issue by psiotwo** [obophenotype/bio-attribute-ontology#169]
After the release yesterday http://purl.obolibrary.org/obo/oba.owl goes to https://github.com/obophenotype/bio-attribute-ontology/releases/download/v2022-11-26/oba.owl which ends up with 404

**Comment by matentzn** [comment]
Sorry, forgot I needed to to attach the release files.. Doing asap.

**Comment by matentzn** [comment]
Thank you @psiotwo for letting me know!
