### ISSUE TITLE
Slurp up MP terms into OBA relevant for IMPC

### ISSUE THREAD

**Issue by matentzn** [obophenotype/bio-attribute-ontology#176]
The goal of this issue is to slurp up all terms _relevant to IMPC_ (used to describe mouse knockouts) into OBA by basically checking parsing the relevant EQ statements and copying them here.

## Method

1. Download all matches: https://github.com/obophenotype/upheno-dev/tree/master/src/curation/pattern-matches/mp
1. For every table in 1, only print rows that are in [impc_terms.txt](https://github.com/obophenotype/bio-attribute-ontology/files/10197007/impc_terms.txt)
1. make a PR on this repo here, adding all tables to `src/patterns/data/impc/*.tsv` as _tsv_ files
1. share statistics here: how many terms have a row in one of the tables, how many don't.

**Comment by souzadevinicius** [comment]
| name                                                                | length_terms | length_shared_impc_terms |
|---------------------------------------------------------------------|--------------|--------------------------|
| abnormallyIncreasedRateOfBiologicalProcess                          |           53 |                       14 |
| abnormalConcentrationOfChemicalEntityInLocation                     |            0 |                        0 |
| abnormallyIncreasedRateOfMolecularFunction                          |           30 |                        0 |
| disorganizedAnatomicalEntity                                        |           20 |                        0 |
| hyperplasticAnatomicalEntity                                        |           90 |                        0 |
| abnormalFunctionalityOfPartOfAnatomicalEntity                       |            0 |                        0 |
| lesionedAnatomicalEntity                                            |            0 |                        0 |
| abnormallyInvertedAnatomicalEntityInLocation                        |            0 |                        0 |
| prematureClosureOfAnatomicalEntity                                  |           12 |                        0 |
| abnormallyEvertedAnatomicalEntity                                   |            3 |                        0 |
| abnormallyPunctateAnatomicalEntity                                  |            0 |                        0 |
| decreasedProportionOfCellTypeInLocation                             |            0 |                        0 |
| abnormallyDecreasedOccurrenceOfBiologicalProcessInLocation          |            0 |                        0 |
| hypoplasticAnatomicalEntityInLocation                               |            0 |                        0 |
| abnormallyDecreasedMassDensityOfAnatomicalEntity                    |            1 |                        1 |
| abnormallyDecreasedRateOfMolecularFunction                          |           30 |                        0 |
| abnormallyDecreasedMotilityOfCellularComponentInLocation            |            0 |                        0 |
| abnormalCellularComponentProcess                                    |            0 |                        0 |
| abnormallyDuplicatedAnatomicalEntity                                |            4 |                        0 |
| abnormallyIncreasedQualityOfBiologicalProcessInLocation             |            4 |                        0 |
| abnormalMorphologyOfPartOfAnatomicalEntity                          |           13 |                        0 |
| abnormallyDelayedBiologicalProcess                                  |           23 |                        0 |
| abnormallyIncreasedWidthOfAnatomicalEntity                          |           24 |                        1 |
| abnormalCoilingOfAnatomicalEntity                                   |            1 |                        0 |
| abnormallyDecreasedResistanceOfWholeOrganismToEntity                |            0 |                        0 |
| abnormallyDecreasedThicknessOfAnatomicalEntity                      |           71 |                        9 |
| abnormalBiologicalProcessInLocation                                 |            9 |                        0 |
| abnormallyOpenAnatomicalEntity                                      |            4 |                        0 |
| abnormalBiologicalProcess                                           |            7 |                        0 |
| abnormallyPunctateAnatomicalEntityInLocation                        |            0 |                        0 |
| atrophiedAnatomicalEntity                                           |           50 |                        0 |
| abnormalMolecularFunction                                           |            0 |                        0 |
| abnormallyDecreasedFunctionalityOfAnatomicalEntity                  |            7 |                        0 |
| abnormalNumberOfCellularComponent                                   |           10 |                        0 |
| blisteredAnatomicalEntity                                           |            1 |                        0 |
| abnormallyDecreasedQualityOfBiologicalProcessInLocation             |            5 |                        0 |
| abnormallyDilatedAnatomicalEntity                                   |           72 |                        3 |
| abnormalAbsenceOfAnatomicalEntityDueToDegeneration                  |            0 |                        0 |
| abnormallyDecreasedEfficacyOfProteinLocalizationInCellularComponent |            0 |                        0 |
| neoplasticAnatomicalEntity                                          |            0 |                        0 |
| abnormallyDecreasedRateOfBehavior                                   |           38 |                       14 |
| bifurcatedAnatomicalEntity                                          |            6 |                        0 |
| abnormalFunctionalityOfAnatomicalEntity                             |          115 |                        3 |
| abnormalAbsenceOfMolecularFunction                                  |            0 |                        0 |
| abnormalNumberOfAnatomicalEntity                                    |           25 |                        1 |
| abnormallyDecreasedDistanceBetweenAnatomicalEntities                |            0 |                        0 |
| cystInLocation                                                      |           37 |                        0 |
| abnormalAnatomicalEntityNotParts                                    |           78 |                        6 |
| necroticAnatomicalEntity                                            |            0 |                        0 |
| abnormallyIncreasedEfficacyOfBehavior                               |            0 |                        0 |
| edematousAnatomicalEntity                                           |           18 |                        1 |
| ivoryAnatomicalEntity                                               |            0 |                        0 |
| abnormalArrestedDevelopmentDuringStage                              |            0 |                        0 |
| abnormallyIncreasedWeightOfAnatomicalEntity                         |           54 |                       14 |
| abnormallyIncreasedMotilityOfCellularComponentInLocation            |            0 |                        0 |
| abnormallyIncreasedFunctionalityOfAnatomicalEntityInLocation        |            0 |                        0 |
| irregularMassDensityOfAnatomicalEntity                              |            0 |                        0 |
| abnormalHeightOfAnatomicalEntity                                    |            1 |                        0 |
| abnormallyIncreasedMassDensityOfAnatomicalEntity                    |            1 |                        1 |
| abnormallyProtrudingAnatomicalEntityInLocation                      |            0 |                        0 |
| abnormallyDecreasedPigmentationOfAnatomicalEntity                   |            1 |                        0 |
| abnormallyDecreasedNumberOfAnatomicalEntity                         |           54 |                        7 |
| abnormallyIncreasedLengthOfAnatomicalEntity                         |           40 |                       10 |
| abnormallyDecreasedQualityOfBiologicalProcess                       |            5 |                        0 |
| abnormalShapeOfAnatomicalEntityByShapeTypeInLocation                |            0 |                        0 |
| malformedAnatomicalEntity                                           |            1 |                        0 |
| abnormallyPatchyPigmentationOfAnatomicalEntity                      |            0 |                        0 |
| abnormalColorOfAnatomicalEntityByColor                              |           14 |                        4 |
| bifurcatedAnatomicalEntityInLocation                                |            0 |                        0 |
| abnormallyDecreasedNumberOfAnatomicalEntityInLocation               |            8 |                        3 |
| abnormallyDecreasedVolumeOfAnatomicalEntity                         |            9 |                        1 |
| abnormallyPrematureBiologicalProcess                                |            9 |                        0 |
| abnormallyDecreasedLevelOfChemicalEntityInLocation                  |          163 |                       27 |
| abnormallyIncreasedLevelOfChemicalEntityWithRole                    |            0 |                        0 |
| abnormallyIncreasedCoilingOfAnatomicalEntity                        |            0 |                        0 |
| abnormalPositionOfAnatomicalEntityInLocation                        |            0 |                        0 |
| abscessInLocation                                                   |            3 |                        0 |
| abnormallyIncreasedOccurrenceOfBiologicalProcessInLocation          |            0 |                        0 |
| abnormallyIncreasedResistanceOfWholeOrganismToEntity                |            0 |                        0 |
| abnormallyIncreasedMobilityOfAnatomicalEntity                       |            0 |                        0 |
| abnormalRateOfBiologicalProcessBeforeStage                          |            0 |                        0 |
| decreasedProportionOfCellTypeTowardsCellTypeInLocation              |            0 |                        0 |
| abnormallyDecreasedWidthOfAnatomicalEntityInLocation                |            0 |                        0 |
| lysedAnatomicalEntity                                               |            0 |                        0 |
| fibroticAnatomicalEntity                                            |            0 |                        0 |
| abnormallyDecreasedFunctionalityOfAnatomicalEntityInLocation        |            0 |                        0 |
| abnormalLevelOfChemicalEntity                                       |          113 |                        0 |
| paralysedAnatomicalEntity                                           |            7 |                        0 |
| abnormallyDecreasedSizeOfAnatomicalEntity                           |          293 |                       32 |
| abnormallyDecreasedNumberOfCellularComponent                        |            9 |                        0 |
| abnormallyDecreasedLevelOfChemicalEntity                            |           68 |                        0 |
| abnormalResistanceOfWholeOrganismToEntity                           |            0 |                        0 |
| abnormallyDelayedBiologicalProcessInLocation                        |            5 |                        0 |
| abnormalHasFewerPartsOfTypeAnatomicalEntity                         |            0 |                        0 |
| abnormalHasExtraPartsOfTypeAnatomicalEntityInLocation               |            0 |                        0 |
| abnormallyClosedAnatomicalEntity                                    |            2 |                        1 |
| brokenAnatomicalEntity                                              |            6 |                        0 |
| abnormallyIncreasedNumberOfAnatomicalEntityInLocation               |           10 |                        2 |
| abnormallyDecreasedRateOfBiologicalProcess                          |           65 |                       16 |
| abnormalMassDensityOfAnatomicalEntity                               |            1 |                        1 |
| abnormalShapeOfPhysicalEntity                                       |           14 |                        5 |
| abnormallyIncreasedEfficacyOfProteinLocalizationInCellularComponent |            0 |                        0 |
| abnormallyIncreasedThicknessOfAnatomicalEntityInLocation            |            2 |                        0 |
| aplasticHypoplasticAnatomicalEntity                                 |            0 |                        0 |
| abnormalAbsenceOfAnatomicalEntityInLocation                         |          178 |                        6 |
| abnormallyFusedAnatomicalEntities                                   |           50 |                        6 |
| abnormallyIncreasedLengthOfAnatomicalEntityInLocation               |            0 |                        0 |
| abnormalMobilityOfAnatomicalEntity                                  |            1 |                        0 |
| abnormallyDecreasedSpeedOfAnatomicalEntity                          |            0 |                        0 |
| abnormalLevelOfChemicalEntityWithRoleInLocation                     |            0 |                        0 |
| abnormallyIncreasedMassDensityOfAnatomicalEntityInLocation          |            0 |                        0 |
| abnormallyIncreasedVolumeOfAnatomicalEntity                         |           10 |                        1 |
| abnormallyDecreasedStrengthOfAnatomicalEntity                       |            6 |                        1 |
| abnormallyIncreasedQualityOfBiologicalProcess                       |            4 |                        0 |
| abnormallyDecreasedMassOfAnatomicalEntity                           |           55 |                       14 |
| abnormallyDecreasedOccurrenceOfBiologicalProcess                    |            0 |                        0 |
| abnormalEfficacyOfProteinLocalizationInCellularComponent            |            0 |                        0 |
| abnormallyDecreasedPositionOfAnatomicalEntity                       |            1 |                        1 |
| abnormallyIncompleteClosureOfAnatomicalEntity                       |           13 |                        0 |
| abnormallyApoptoticAnatomicalEntityInLocation                       |            0 |                        0 |
| abnormalRateOfBiologicalProcessInLocation                           |            4 |                        0 |
| mislocalisedAnatomicalEntity                                        |           24 |                        0 |
| abnormalMorphologyOfAnatomicalEntity                                |         1781 |                      117 |
| abnormalShapeOfAnatomicalEntityByShapeType                          |          128 |                       13 |
| abnormallyIncreasedSpeedOfAnatomicalEntity                          |            0 |                        0 |
| abnormallyDecreasedWidthOfAnatomicalEntity                          |           12 |                        2 |
| abnormalDistanceBetweenAnatomicalEntities                           |            0 |                        0 |
| abnormalDegenerationOfAnatomicalEntityInLocation                    |            0 |                        0 |
| abnormalAbsenceOfBehavior                                           |            9 |                        4 |
| abnormallyIncreasedOccurrenceOfBiologicalProcess                    |            0 |                        0 |
| abnormalStabilityOfAnatomicalEntity                                 |            0 |                        0 |
| mislocalisedAnatomicalEntityInLocation                              |            0 |                        0 |
| abnormallyIncreasedHeightOfAnatomicalEntity                         |            4 |                        0 |
| hypertrophicAnatomicalEntity                                        |           29 |                        0 |
| abnormallyPrematureBiologicalProcessInLocation                      |            0 |                        0 |
| abnormallyDecreasedSizeOfCellularComponent                          |            3 |                        0 |
| abnormallyDecreasedLengthOfAnatomicalEntityAttachedToLocation       |            0 |                        0 |
| calcifiedAnatomicalEntity                                           |           22 |                        0 |
| abnormalSizeOfCellularComponent                                     |            2 |                        0 |
| abnormalRateOfDevelopmentDuringStage                                |            0 |                        0 |
| abnormalAbsenceOfBiologicalProcessInLocation                        |           12 |                        1 |
| abnormallyAsymmetricalAnatomicalEntity                              |            7 |                        0 |
| abnormalRateOfBiologicalProcess                                     |            3 |                        1 |
| abnormallyIncreasedHeightOfAnatomicalEntityInLocation               |            0 |                        0 |
| abnormalCellProliferationActingOnCellsOfTypeInLocation              |            0 |                        0 |
| abnormallyDecreasedRateOfBiologicalProcessInLocation                |           17 |                        0 |
| fracturedAnatomicalEntityByFractureType                             |            0 |                        0 |
| abnormalMorphologyOfCellularComponent                               |           85 |                        0 |
| abnormalCellProliferationActingOnCellsOfType                        |            0 |                        0 |
| abnormalAgenesisOfAnatomicalEntity                                  |            0 |                        0 |
| ivoryAnatomicalEntityInLocation                                     |            0 |                        0 |
| abnormalMorphologyOfAnatomicalEntityInLocation                      |            0 |                        0 |
| blisteredAnatomicalEntityInLocation                                 |            0 |                        0 |
| abnormallyIncreasedRateOfBehavior                                   |           35 |                       12 |
| abnormallyDecreasedResistanceOfWholeOrganismToChemicalEntity        |            0 |                        0 |
| abnormallyDetachedAnatomicalEntities                                |            4 |                        0 |
| abnormalMassDensityOfAnatomicalEntityInLocation                     |            0 |                        0 |
| malformedAnatomicalEntityInLocation                                 |            0 |                        0 |
| abnormallyBentAnatomicalEntity                                      |            2 |                        0 |
| abnormalFunctionalityOfCellularComponent                            |            9 |                        0 |
| abnormallyIncreasedStabilityOfAnatomicalEntity                      |            0 |                        0 |
| abnormallyRotatedAnatomicalEntity                                   |            1 |                        1 |
| hypoplasticAnatomicalEntity                                         |          195 |                        0 |
| abnormalPositionOfAnatomicalEntity                                  |           41 |                        3 |
| metaplasticAnatomicalEntity                                         |            0 |                        0 |
| abnormalCellularComponent                                           |            0 |                        0 |
| abnormalBehavior                                                    |            3 |                        0 |
| abnormalProportionOfCellTypeInLocation                              |            0 |                        0 |
| abnormallyIncreasedRateOfBiologicalProcessInLocation                |           13 |                        0 |
| abnormallyDecreasedEfficacyOfBehavior                               |            0 |                        0 |
| abnormalLevelOfChemicalEntityWithRole                               |            0 |                        0 |
| abnormalDevelopmentOfAnatomicalEntity                               |            0 |                        0 |
| abnormallyDecreasedCoilingOfAnatomicalEntity                        |            1 |                        0 |
| abnormallyCurvedAnatomicalEntityByOrientation                       |           17 |                        1 |
| fracturedAnatomicalEntity                                           |            0 |                        0 |
| abnormallyIncreasedLevelOfChemicalEntityInLocation                  |          205 |                       29 |
| damagedAnatomicalEntityInLocation                                   |            0 |                        0 |
| increasedProportionOfCellTypeInLocation                             |            0 |                        0 |
| abnormalConcentrationOfChemicalEntity                               |            0 |                        0 |
| abnormallyIncreasedSizeOfAnatomicalEntityInLocation                 |            0 |                        0 |
| abnormalPersistenceOfAnatomicalEntity                               |            0 |                        0 |
| abnormalWeightOfAnatomicalEntity                                    |           38 |                       13 |
| malformedAnatomicalEntityByType                                     |            1 |                        0 |
| abnormalCellDifferentiation                                         |            0 |                        0 |
| abnormallyFusedAnatomicalEntitiesInLocation                         |            0 |                        0 |
| abnormalAnatomicalEntity                                            |            0 |                        0 |
| abnormallyIncreasedSizeOfCellularComponent                          |            4 |                        0 |
| abnormalAbsenceOfProteinLocalizationInCellularComponent             |            0 |                        0 |
| abnormallyIncreasedDistanceBetweenAnatomicalEntities                |            0 |                        0 |
| abnormalAbsenceOfMotilityOfCellularComponentInLocation              |            0 |                        0 |
| atreticAnatomicalEntity                                             |           21 |                        0 |
| abnormallyIncreasedPigmentationOfAnatomicalEntity                   |            1 |                        0 |
| abnormallyArrestedBiologicalProcess                                 |            7 |                        0 |
| abnormallyIncreasedThicknessOfAnatomicalEntity                      |           58 |                        9 |
| aplasticAnatomicalEntity                                            |            0 |                        0 |
| abnormalSpatialPatternOfAnatomicalEntity                            |            5 |                        2 |
| abnormalConstrictionOfAnatomicalEntity                              |           43 |                        1 |
| abnormalAbsenceOfBiologicalProcess                                  |           41 |                        5 |
| abnormalSizeOfAnatomicalEntity                                      |           66 |                       10 |
| abnormallyIncreasedNumberOfCellularComponent                        |           12 |                        0 |
| abnormalColorOfAnatomicalEntity                                     |            8 |                        2 |
| abnormallyDecreasedMobilityOfAnatomicalEntity                       |            1 |                        0 |
| abnormallyApoptoticAnatomicalEntity                                 |            0 |                        0 |
| abnormallySegmentedAnatomicalEntityInLocation                       |            0 |                        0 |
| abnormalNumberOfAnatomicalEntityInLocation                          |            1 |                        0 |
| abnormalAbsenceOfChemicalEntity                                     |            2 |                        0 |
| abnormalCellProliferationInAnatomicalEntity                         |            0 |                        0 |
| abnormalProportionOfCellTypeTowardsCellTypeInLocation               |            0 |                        0 |
| abnormallyIncreasedLevelOfChemicalEntity                            |           69 |                        0 |
| abnormallyDecreasedSizeOfAnatomicalEntityInLocation                 |            0 |                        0 |
| abnormallyDuplicatedAnatomicalEntityInLocation                      |            0 |                        0 |
| abnormallyIncreasedNumberOfAnatomicalEntity                         |           43 |                        4 |
| abnormallyDecreasedLengthOfAnatomicalEntityInLocation               |            0 |                        0 |
| abnormallyDecreasedLevelOfChemicalEntityWithRole                    |            0 |                        0 |
| abnormallyDecreasedTonicityOfAnatomicalEntity                       |            1 |                        0 |
| abnormalHasFewerPartsOfTypeAnatomicalEntityInLocation               |            0 |                        0 |
| abnormalLevelOfChemicalEntityInLocation                             |          171 |                       30 |
| abnormalHasExtraPartsOfTypeAnatomicalEntity                         |            3 |                        2 |
| abnormallyIncreasedSizeOfAnatomicalEntity                           |          215 |                       32 |
| abnormalPigmentationOfAnatomicalEntity                              |            0 |                        0 |
| abnormalAbsenceOfPigmentationOfAnatomicalEntity                     |            0 |                        0 |
| abnormallyDecreasedLevelOfChemicalEntityWithRoleInLocation          |            0 |                        0 |
| abnormallyIncreasedWidthOfAnatomicalEntityInLocation                |            0 |                        0 |
| abnormallyIncreasedLevelOfChemicalEntityWithRoleInLocation          |            0 |                        0 |
| abnormallyDecreasedLengthOfAnatomicalEntity                         |           74 |                       10 |
| abnormallyDecreasedWeightOfAnatomicalEntity                         |           55 |                       14 |
| abnormallyArrestedBiologicalProcessInLocation                       |            0 |                        0 |
| abnormalAbsenceOfChemicalEntityInLocation                           |            2 |                        0 |
| abnormalDegenerationOfCellularComponentInLocation                   |            0 |                        0 |
| dysplasticAnatomicalEntity                                          |            7 |                        0 |
| abnormallyImmobileAnatomicalEntity                                  |            0 |                        0 |
| abnormalMotilityOfCellularComponent                                 |            0 |                        0 |
| abnormallyIncreasedResistanceOfWholeOrganismToChemicalEntity        |            0 |                        0 |
| increasedProportionOfCellTypeTowardsCellTypeInLocation              |            0 |                        0 |
| abnormallyProminentAnatomicalEntity                                 |            6 |                        0 |
| abnormalDegenerationOfAnatomicalEntity                              |           53 |                        1 |
| abnormalDegenerationOfCellularComponent                             |            3 |                        0 |
| abnormallyDecreasedStabilityOfAnatomicalEntity                      |            0 |                        0 |
| abnormalAbsenceOfAnatomicalEntity                                   |          423 |                        7 |
| abnormallyDecreasedHeightOfAnatomicalEntity                         |            7 |                        0 |

**Comment by matentzn** [comment]
Very nice! Out of all the IMPC terms, how many can be found _anywhere_ in any of the tables? (total number and percentage)?

**Comment by souzadevinicius** [comment]
Completed in this issue #182
