### ISSUE TITLE
Assign PATO qualifiers to new IMPC base terms

### ISSUE THREAD

**Issue by souzadevinicius** [obophenotype/bio-attribute-ontology#182]
@ar-ibrahim, here it is the IMPC filtered-based terms: [impc_terms.tsv](https://docs.google.com/spreadsheets/d/13UZVY5YxIZom-sS-TDuPSXet8sdtzo1OwQ4LYxrZVrI/edit?usp=sharing)

**Comment by ar-ibrahim** [comment]
Hi @rays22. For this [IMPC terms list](https://docs.google.com/spreadsheets/d/13UZVY5YxIZom-sS-TDuPSXet8sdtzo1OwQ4LYxrZVrI/edit#gid=0) can you please take a general look at my assigned PATO terms (columns B & C) and let me know if you have any comments? Thank you.
