### ISSUE TITLE
Fix unsats in 2022-12-21 Release

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#186]
Fix the class definitions that lead to logical contradictions:

Find and fix the class definition(s) that lead to logical contradictions.
1. [estrogen secretion](http://purl.obolibrary.org/obo/GO_0035937)
2. [negative regulation of estrogen secretion](http://purl.obolibrary.org/obo/GO_2000862)
3. [positive regulation of estrogen secretion](http://purl.obolibrary.org/obo/GO_2000863)
4. [regulation of estrogen secretion](http://purl.obolibrary.org/obo/GO_2000861)

**Comment by rays22** [comment]
The unsatisfiable classes are due to the  [material entity BFO:0000040](https://www.ebi.ac.uk/ols/ontologies/bfo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000040) range restriction of [has input RO:0002233](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002233).
Actually, this range restriction of [RO:0002233](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002233) has been relaxed in RO.
It seems that the **outdated range restriction** of [RO:0002233](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002233) is coming from an external ontology import (or imports) into OBA. My candidate for the source of the outdated [RO:0002233](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002233) range restriction problem is the Plant Trait Ontology import (`po_import.owl`).
![estrogen_secretion-UNSAT](https://user-images.githubusercontent.com/25171986/211853674-275f031e-619f-4952-91fc-6e95f0709af3.jpg)

**Comment by rays22** [comment]
I have refreshed in #187 , but it seems it has not fixed the unsats.

    sh run.sh make refresh-merged

**Comment by rays22** [comment]
Only `merged_import.owl` and `oba.obo` have the offending axioms for these GO classes within the OBA repo.

The GO classes in `go-plus.owl` version 2023-01-01 look fine, because `go-plus.owl` does not have the outdated [material entity BFO:0000040](https://www.ebi.ac.uk/ols/ontologies/bfo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000040) range restriction of [has input RO:0002233](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002233).

If OBA used the latest [RO:0002233](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_000223) (2023-01-04 release), then the axioms would be fine in OBA too.
I expected that refreshing the merged imports would fix the unsats, but it did not.

**Comment by matentzn** [comment]
Lets prioritise this after the paper submission. The culprit is either Uberon or GO plus, but a quick check didn't tell me

**Comment by matentzn** [comment]
You tried in Protege as well?

**Comment by rays22** [comment]
> You tried in Protege as well?

Yes, I did.

**Comment by matentzn** [comment]
Awesome!
