### ISSUE TITLE
Requesting CPATH related OBA traits

### ISSUE THREAD

**Issue by matentzn** [obophenotype/bio-attribute-ontology#191]
| ID | Label |
|-------------|----------------------------------------|
| NBO:0000351 | body coordination                      |
| NBO:0000342 | limb coordination                      |
| NBO:0000346 | upper limb coordination                |
| NBO:0000345 | lower limb coordination                |
| NBO:0000339 | motor coordination                     |
| NBO:0000347 | gross motor coordination               |
| NBO:0000348 | fine motor coordination                |
| NBO:0000341 | eye-hand coordination                  |
| OBA:XXXXXX1 | whole organism stability               |
| OBA:XXXXXX2 | facial muscle performance              |
| OBA:XXXXXX3 | peripheral nervous system function     |
| OBA:XXXXXX4 | knee joint functionality               |
| OBA:XXXXXX5 | ankle joint functionality              |
| OBA:XXXXXX6 | tendon of biceps brachii functionality |
| OBA:XXXXXX7 | brachioradialis functionality          |

@Daniel-Olson 

Can you provide:

1. Uberon terms (with labels and Ids) for all of these?
2. PATO qualities (with labels and ids) for all of these?

I will deal with politics around NBO.

**Comment by Daniel-Olson** [comment]
@matentzn I couldn't find comparable terms in Uberon for fine-motor/eye-hand and two of the motor terms from NBO are already being used by Uberon. 


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/dolson/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/dolson/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



ID | Label | Uberon_ID | Uberon_Label | PATO_ID | PATO_Label
-- | -- | -- | -- | -- | --
NBO:0000351 | body coordination | UBERON:0000468 | multicellular organism | PATO:0000188 | coordination
NBO:0000342 | limb coordination | UBERON:0002101 | limb | PATO:0000188 | coordination
NBO:0000346 | upper limb coordination | UBERON:0002102 | forelimb | PATO:0000188 | coordination
NBO:0000345 | lower limb coordination | UBERON:0002103 | hindlimb | PATO:0000188 | coordination
NBO:0000339 | motor coordination | NBO:0000339 | motor coordination | PATO:0000188 | coordination
NBO:0000347 | gross motor coordination | NBO:0000347 | gross motor coordination | PATO:0000188 | coordination
NBO:0000348 | fine motor coordination | x | x | PATO:0000188 | coordination
NBO:0000341 | eye-hand coordination | x | x | PATO:0000188 | coordination
OBA:XXXXXX1 | whole organism stability | UBERON:0000468 | multicellular organism | PATO:0015026 | stability
OBA:XXXXXX2 | facial muscle performance | UBERON:0001577 | facial muscle | PATO:0001509 | functionality
OBA:XXXXXX3 | peripheral nervous system   function | UBERON:0000010 | peripheral nervous system | PATO:0001509 | functionality
OBA:XXXXXX4 | knee joint functionality | UBERON:0001485 | knee joint | PATO:0001509 | functionality
OBA:XXXXXX5 | ankle joint functionality | UBERON:0001488 | ankle joint | PATO:0001509 | functionality
OBA:XXXXXX6 | tendon of biceps brachii   functionality | UBERON:0008188 | tendon of biceps brachii | PATO:0001509 | functionality
OBA:XXXXXX7 | brachioradialis functionality | UBERON:0011011 | brachioradialis | PATO:0001509 | functionality



</body>

</html>

**Comment by matentzn** [comment]
Excellent @Daniel-Olson 

>  couldn't find comparable terms in Uberon for fine-motor/eye-hand and two of the motor terms from NBO are already being used by Uberon.

1. If the term does not specify a specific anatomical system, we can link it to "UBERON:anatomical entity"
2. eye-hand coordination is an interesting case. @rays22 do you have an idea how to best represent these?

> gross motor coordination	

All the values in this column should be Uberon - what anatomical system is meant when we say "motor coordination"? Skeletal system? Muscular system? Any anatomical part? Any muscle? Any limb?

When you are done with the above, can you (maybe with Emily's help) make a PR adding these new terms in the appropriate columns here: https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/data/default/entity_attribute.tsv

Note that it is important that the diff of that file really only encompasses your added rows (not all rows, because for example, you change the line endings or something).

**Comment by Daniel-Olson** [comment]
@matentzn the motor/eye-hand coordination terms were originally subclasses of upper/lower limb coordination but as the mapping template evolved they were deprecated. So we can map them broadly to the terms below for potential future use or it might make the most sense to just leave them out for now and worry about them if they ever resurface? 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/dolson/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/dolson/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



ID | Label | Uberon_ID | Uberon_Label | PATO_ID | PATO_Label
-- | -- | -- | -- | -- | --
NBO:0000351 | body coordination | UBERON:0000468 | multicellular organism | PATO:0000188 | coordination
NBO:0000342 | limb coordination | UBERON:0002101 | limb | PATO:0000188 | coordination
NBO:0000346 | upper limb coordination | UBERON:0002102 | forelimb | PATO:0000188 | coordination
NBO:0000345 | lower limb coordination | UBERON:0002103 | hindlimb | PATO:0000188 | coordination
NBO:0000339 | motor coordination | UBERON:0025525 | motor system | PATO:0000188 | coordination
NBO:0000347 | gross motor coordination | UBERON:0025525 | motor system | PATO:0000188 | coordination
NBO:0000348 | fine motor coordination | UBERON:0025525 | motor system | PATO:0000188 | coordination
NBO:0000341 | eye-hand coordination | UBERON:0001062 | anatomical entity | PATO:0000188 | coordination
OBA:XXXXXX1 | whole organism stability | UBERON:0000468 | multicellular organism | PATO:0015026 | stability
OBA:XXXXXX2 | facial muscle performance | UBERON:0001577 | facial muscle | PATO:0001509 | functionality
OBA:XXXXXX3 | peripheral nervous system   function | UBERON:0000010 | peripheral nervous system | PATO:0001509 | functionality
OBA:XXXXXX4 | knee joint functionality | UBERON:0001485 | knee joint | PATO:0001509 | functionality
OBA:XXXXXX5 | ankle joint functionality | UBERON:0001488 | ankle joint | PATO:0001509 | functionality
OBA:XXXXXX6 | tendon of biceps brachii   functionality | UBERON:0008188 | tendon of biceps brachii | PATO:0001509 | functionality
OBA:XXXXXX7 | brachioradialis functionality | UBERON:0011011 | brachioradialis | PATO:0001509 | functionality



</body>

</html>

**Comment by matentzn** [comment]
I think this is reasonable (leaving them out for now). The mapping also looks good. I think you are ready to make a PR now, as described in my previous comment!

**Comment by Daniel-Olson** [comment]
Thanks @matentzn! I have a few questions:
How do I handle the IDs? 
1) Do the NBO IDs remain verbatim or should they be changed to OBA IDs? 
2) I looked through the other bio-attribute PRs and I see that they all have OBA IDs but I didn't see a place to reserve IDs for new terms. Do I just need to come up with IDs that don't already exist or do I just commit the PR with 'OBA:xxxxxx" IDs and allow the OBA folks to assign correct IDs? 
3) Lastly the contributing.md file recommends creating detailed requests for new terms. Isn't a PR skipping this step?
Thanks!

**Comment by matentzn** [comment]
> Do the NBO IDs remain verbatim or should they be changed to OBA IDs?

Change to OBA IDs.

> I looked through the other bio-attribute PRs and I see that they all have OBA IDs but I didn't see a place to reserve IDs for new terms. Do I just need to come up with IDs that don't already exist or do I just commit the PR with 'OBA:xxxxxx" IDs and allow the OBA folks to assign correct IDs?

Make a PR here: https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/ontology/oba-idranges.owl, copy an existing range and adopt it to assign yourself one as well. Once the PR is there, I can fix it for you, so don't worry about making mistakes!

> Lastly the contributing.md file recommends creating detailed requests for new terms with definitions and PMIDs. Can I go straight to a PR without this step?

No its fine, the terms you request are pretty standard OBA, no need for a detailed issue. Thanks!

**Comment by rays22** [comment]
> 2\. eye-hand coordination is an interesting case. @rays22 do you have an idea how to best represent these?
> 
> > gross motor coordination
> 
> All the values in this column should be Uberon - what anatomical system is meant when we say "motor coordination"? Skeletal system? Muscular system? Any anatomical part? Any muscle? Any limb?


The [NBO:0000339 motor coordination](https://www.ebi.ac.uk/ols/ontologies/NBO/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNBO_0000339) definition looks correct to me, because motor coordination is a process. It is this process that should bear the quality, not the anatomical entities. The anatomical entities like the hand, eye limbs are just participants in the process.
[PATO:0000188 coordination](https://www.ebi.ac.uk/ols/ontologies/PATO/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000188) is an organismal quality. Our hands or limbs just participate in the process.
The 'anatomical entity - coordination' pairs other than the 'UBERON:0000468 | multicellular organism | PATO:0000188 | coordination' pair do not look right to me.

Anatomical entities can be bearers of the other PATO qualities in the table above.

**Comment by matentzn** [comment]
@rays22 thank you for your excellent and careful review. How would you define `upper limb motor coordination trait`?

**Comment by rays22** [comment]
> @rays22 thank you for your excellent and careful review. How would you define `upper limb motor coordination trait`?

@matentzn , I would define it as a process quality:

NBO:0000346 upper limb coordination PATO:0000001 quality

**Comment by rays22** [comment]
> Could you redefine the coordination traits using the pattern you suggest?

Yes, I could. I would use the quality [PATO:0015002 process efficacy](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0015002&lang=en&viewMode=PreferredRoots&siblings=false).

**Comment by matentzn** [comment]
Interesting! Ok! Let's do it, and see how others react when they come across this, and maybe check MP, ZP and HP if they make use of the NBO terms in their defs. It seems we should be compatible with whatever they are doing :) THANKS!
