### ISSUE TITLE
Map sleep-related EFO terms

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#209]
- [x] add new terms
- [x] add mapped terms to [mapping table](https://docs.google.com/spreadsheets/d/13qh7dLE38vMyz91oRqj6GzKjFohNazNKAJxKG6Plw1o/edit#gid=1005741851)
Map 'sleep' related traits from [oba-efo-unreviewed.dosdp.tsv](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/mappings/oba-efo-unreviewed.dosdp.tsv):

subject_id | subject_label | match_type | quality | quality_label | attribute | attribute_label
-- | -- | -- | -- | -- | -- | --
EFO:0005273 | sleep depth | Lexical | PATO:0001595 | depth | GO:0030431 | sleep
EFO:0004870 | sleep measurement | Lexical | PATO:0000001 | quality | GO:0030431 | sleep
EFO:0005274 | sleep time | Lexical | PATO:0000165 | time | GO:0030431 | sleep
EFO:0007817 | sleep apnea measurement | Lexical | PATO:0000001 | quality | GO:0030431 | sleep
EFO:0008455 | sleep apnea measurement during REM sleep | Lexical | PATO:0000001 | quality | GO:0030431 | sleep
EFO:0004807 | short sleep | Lexical | PATO:0000574 | short | GO:0030431 | sleep
EFO:0008456 | sleep apnea measurement during non-REM sleep | Lexical | PATO:0000001 | quality | GO:0030431 | sleep
EFO:0005272 | sleep quality | Lexical | PATO:0000001 | quality | GO:0030431 | sleep
EFO:0005271 | sleep duration | Lexical | PATO:0001309 | duration | GO:0030431 | sleep
EFO:0005280 | sleep latency | Lexical | PATO:0001005 | latency | GO:0030431 | sleep

**Comment by rays22** [comment]
I did not add or map the following EFO measurement terms to OBA, because they refer to deviation from normal phenotypes, so they are not in scope for OBA:

EFO:0007817 | rdfs:label | sleep apnea measurement | deviation (from_normal) | consider HP:0010535 Sleep apnea |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
EFO:0008455 | rdfs:label | sleep apnea measurement during REM sleep | deviation (from_normal) | consider HP:0010535 Sleep apnea |   |   |   |   |  
EFO:0004807 | rdfs:label | short sleep | deviation (from_normal) | consider HP:0033063 Shortened sleep cycle |   | GO:0030431 | sleep | PATO:0001309 | duration
EFO:0008456 | rdfs:label | sleep apnea measurement during non-REM sleep | deviation (from_normal) | consider HP:0010535 Sleep apnea |   |   |   |   |

**Comment by matentzn** [comment]
Excellent thinking!
