### ISSUE TITLE
EFO-OBA mapping (behaviour traits)

### ISSUE THREAD

**Issue by ar-ibrahim** [obophenotype/bio-attribute-ontology#220]
- will map terms from [oba-efo-unreviewed.dosdp.tsv](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/mappings/oba-efo-unreviewed.dosdp.tsv)
- filtered by **attribute_labels**: _behavior_, _behaviour_, _reproductive behaviour_.

subject_id | subject_label | match_type | quality | quality_label | attribute | attribute_label
-- | -- | -- | -- | -- | -- | --
EFO:0007663 | childhood   aggressive behaviour measurement | Lexical | PATO:0000001 | quality | GO:0007610 | behaviour
EFO:0009480 | coping behaviour   measurement | Lexical | PATO:0000001 | quality | GO:0007610 | behaviour
EFO:0005671 | smoking behaviour   measurement | Lexical | PATO:0000001 | quality | GO:0007610 | behaviour
EFO:0007052 | antisocial   behaviour measurement | Lexical | PATO:0000001 | quality | GO:0007610 | behaviour
EFO:0006882 | suicide behaviour   measurement | Lexical | PATO:0000001 | quality | GO:0007610 | behaviour
EFO:0007877 | risky sexual   behaviour measurement | Lexical | PATO:0000001 | quality | GO:0007610 | behaviour
EFO:0007862 | reproductive   behaviour measurement | Lexical | PATO:0000001 | quality | GO:0019098 | reproductive   behaviour
EFO:0007826 | aggressive   behaviour measurement | Lexical | PATO:0000001 | quality | GO:0007610 | behaviour
EFO:0008538 | helping behavior   measurement | Lexical | PATO:0000001 | quality | GO:0007610 | behavior
EFO:0004782 | behavior or   behavioral disorder measurement | Lexical | PATO:0000001 | quality | GO:0007610 | behavior
EFO:0007052 | adult antisocial   behaviour measurement | Lexical | PATO:0000001 | quality | GO:0007610 | behaviour

**Comment by ar-ibrahim** [comment]
- Created 3 new OBA terms and added to [entity_attribute_part_of.tsv](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/data/default/entity_attribute_part_of.tsv) 

defined_class | defined_class_name | entity | entity_name | attribute | attribute_name
-- | -- | -- | -- | -- | --
OBA:2050116 | smoking behavior trait | NBO:0015005 | smoking behavior | PATO:0000001 | quality
OBA:2050117 | reproductive behavior trait | NBO:0000010 | reproductive behavior | PATO:0000001 | quality
OBA:2050118 | helping behavior trait | NBO:0000287 | helping behavior | PATO:0000001 | quality

- added mapping to [oba-efo sssom Google sheet](https://docs.google.com/spreadsheets/d/13qh7dLE38vMyz91oRqj6GzKjFohNazNKAJxKG6Plw1o/edit#gid=1005741851)

subject_id | subject_label | subject_category | predicate_id | object_id | object_label | object_category | match_type | subject_source | object_source | confidence | mapping_date | subject_match_field | object_match_field | match_string | author_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
EFO:0007663 | childhood aggressive behaviour measurement | measurement | skos:broadMatch | OBA:1000376 | aggressive behavior   quality | HumanCurated | EFO | OBA | 1 | 2023-02-16 |   |   |   | orcid:0000-0001-6757-4744
EFO:0009480 | coping behaviour measurement | measurement | skos:exactMatch | OBA:1000707 | coping behavior quality |   | HumanCurated | EFO | OBA | 1 | 2023-02-16 |   |   |   | orcid:0000-0001-6757-4744
EFO:0005671 | smoking behaviour measurement | measurement | skos:exactMatch | OBA:2050116 | smoking behavior trait |   | HumanCurated | EFO | OBA | 1 | 2023-02-16 |   |   |   | orcid:0000-0001-6757-4744
EFO:0007052 | antisocial behaviour measurement | measurement | skos:narrowMatch | OBA:1000278 | social inhibition quality |   | HumanCurated | EFO | OBA | 1 | 2023-02-16 |   |   |   | orcid:0000-0001-6757-4744
EFO:0007862 | reproductive behaviour measurement | measurement | skos:exactMatch | OBA:2050117 | reproductive behavior   trait | HumanCurated | EFO | OBA | 1 | 2023-02-16 |   |   |   | orcid:0000-0001-6757-4744
EFO:0007826 | aggressive behaviour measurement | measurement | skos:exactMatch | OBA:1000376 | aggressive behavior   quality | HumanCurated | EFO | OBA | 1 | 2023-02-16 |   |   |   | orcid:0000-0001-6757-4744
EFO:0008538 | helping behavior measurement | measurement | skos:exactMatch | OBA:2050119 | helping behavior trait |   | HumanCurated | EFO | OBA | 1 | 2023-02-16 |   |   |   | orcid:0000-0001-6757-4744
EFO:0007052 | adult antisocial behaviour measurement | measurement | skos:narrowMatch | OBA:1000278 | social inhibition quality |   | HumanCurated | EFO | OBA | 1 | 2023-02-16 |   |   |   | orcid:0000-0001-6757-4744


@rays22 Please review 😊

**Comment by ar-ibrahim** [comment]
- Queries:

The following terms have not been mapped and need to be discussed:

subject_id | subject_label
-- | --
EFO:0006882 | suicide behaviour measurement
EFO:0007877 | risky sexual behaviour measurement
EFO:0004782 | behavior or behavioral disorder measurement



</body>

</html>

**Comment by rays22** [comment]
> * added mappings to [oba-efo sssom Google sheet](https://docs.google.com/spreadsheets/d/13qh7dLE38vMyz91oRqj6GzKjFohNazNKAJxKG6Plw1o/edit#gid=1005741851)

Your EFO-OBA mappings look good to me.
