### ISSUE TITLE
Traits involving proteins and chemicals in blood or serum

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#222]
GWAS is requesting a large number of new EFO terms related to proteins and chemicals in blood or serum.
In order to be able to incorporate them into OBA, I need to assess the size of the task.
- [x] How many new terms are needed?
    - 6104 +/-1000 
- [x] What proportion of the requested terms are proteins?
    - 79.7 %
- [x] What proportion of the protein-related terms have [PRotein Ontology (PRO)](https://www.ebi.ac.uk/ols/ontologies/pr) identifiers?
    - 0%
- [x] What proportion of the terms are chemical-related? 
   - 20.3 %
- [x] What proportion of the chemical-related terms have [ChEBI](https://www.ebi.ac.uk/ols/ontologies/chebi) identifiers?      
    - 0%
- [x] How many chemicals have [SwissLipids](https://www.swisslipids.org) identifiers and is it a trivial task to map them to ChEBI identifiers?
    - 144
    -  ?

**Comment by rays22** [comment]
![megatickets2](https://user-images.githubusercontent.com/25171986/221179231-6deba45d-ea72-4763-ad82-9f6206b94d19.jpg)

1. New term request for Chen PMID:36635386 (WC_20230126) [#1905](https://github.com/EBISPOT/efo/issues/1905)
    - 26 supplementary tables
    - [Supplementary Table 2 Information for the metabolites tested in current study -- ST2](https://www.nature.com/articles/s41588-022-01270-1#Sec36) lists 1091 metabolites (chemicals)
    - Potential identifiers `CAS	CHEMSPIDER	HMDB	HMDB_curated	KEGG	PUBCHEM	PUBCHEM_curated`
        - **NOTE**: no ChEBI or swisslipid identifiers
    - Ticket quotes '415 metabolite terms', but referenced google sheet has 28 terms (as of 2023-02-24).
    - What is the true number of terms needed by GWAS?
2. New Robot term request form for Tabassum PMID 36193934 [#1882](https://github.com/EBISPOT/efo/issues/1882)
    - 146 lipid measurement terms
    - 142 swisslipid IDs
3. New term request for Surapaneni PMID:35870639 (WC_20221117) [#1848](https://github.com/EBISPOT/efo/issues/1848)
    - 4867 protein names
    - 0 identifiers

```tsv
ticket	items	ChEBI/PR
EFO#1905	1091	0
EFO#1882	146	0
EFO#1848	4867	0
```

**Comment by dosumis** [comment]
> What proportion of the protein-related terms have [PRotein Ontology (PRO)](https://www.ebi.ac.uk/ols/ontologies/pr) identifiers?

If you can map to uniprot, you can [generate legal PRO IDs from the uniprot IDs](https://proconsortium.org/pro_comm_Manual_Curation_Guideline.shtml#2.1%20-PRO%20IDs), e.g. https://www.uniprot.org/uniprotkb/P19883/entry -> https://proconsortium.org/app/entry/PR:P19883/.  Uniprot's [ID converter](https://www.uniprot.org/id-mapping) may be useful if other IDs are given.

> Potential identifiers CAS	CHEMSPIDER	HMDB	HMDB_curated	KEGG	PUBCHEM	PUBCHEM_curated

I also see these - which can be used to map to CHEBI.

INCHIKEY | SMILES
-- | --
DWAKNKKXGALPNW-REWHXWOFAV | OC(C1CCC=N1)=O





</html>

**Comment by dosumis** [comment]
Potentially viable workflow:

We provide a list of protein and chemical ID types that we can map easily, building up a set of mapping tools to make this easy.  Where these are provided, we can rapidly generate OBA terms.  Where they are not, we either reject or resort to lexical mappings, living with the fact that these will be unreliable.

**Comment by rays22** [comment]
As per today's discussions at the Monarch/SPOT coord meeting, I am adding 4740 new protein in blood serum trait terms.
After cleaning the curator's table [WC_20221117_measurement
](https://docs.google.com/spreadsheets/d/1wIpe5uAzMzOIgMkLWloNSu_Vp0Z45-pWdIf3ey8FIfk/edit#gid=1909577919) attached to https://github.com/EBISPOT/efo/issues/1848 which has `4762` rows (with 1 header row), I found `4740` unique Uniprot IDs.
The following four IDs are not findable in the current PR:
```
PR:B9ZVM9 Not found. 
PR:Q5JSQ8 Not found. 
PR:Q86SI9 Not found. 
PR:Q9H7B7 Not found. 
```
