### ISSUE TITLE
New term request: 'response to apixaban'

### ISSUE THREAD

**Issue by ar-ibrahim** [obophenotype/bio-attribute-ontology#274]
GWAS Catalog term request related to [Mu PMID: 36867504](https://github.com/EBISPOT/efo/issues/2046)

- [x] **Create OBA term**         
     - [x] Fill in table [response_to_chemical_stimulus_trait.tsv](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/data/default/response_to_chemical_stimulus_trait.tsv) using OBA ID from my range. Use chemical term **[CHEBI:72296](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_72296) apixaban.**
     - [x] Create PR https://github.com/obophenotype/bio-attribute-ontology/pull/275

- [x] **Create a new OBA release**
    The newly created trait terms can be imported into EFO from a publicly released version of OBA.
    To run the OBA release pipeline, follow the instructions in the document [Release Workflow for the Ontology of Biological Attributes (OBA)](https://github.com/obophenotype/bio-attribute-ontology/blob/issue154/docs/OBA_ReleaseWorkflow.md)

- [x] **Provide the new OBA terms to EFO**
    - [x] This step depends on a new public OBA release.
    - [x] You need to accomplish this in an [EFO PR](https://github.com/EBISPOT/efo).
    - [x] Add new OBA term IRIs to [oba_terms.txt](https://github.com/EBISPOT/efo/tree/master/src/ontology/iri_dependencies) that are [to be included](https://github.com/EBISPOT/efo/issues/1382#issuecomment-1117247895) in [EFO dynamic imports.](https://github.com/EBISPOT/efo/blob/master/src/ontology/README-editors.md)
        Use full IRI:
      ```
      http://purl.obolibrary.org/obo/OBA_2050328
      http://purl.obolibrary.org/obo/CHEBI_72296
     ```

**Comment by rays22** [comment]
Hi @ar-ibrahim,
I am closing this issue, because it [seems to have been resolved.](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBA_2050328)
