### ISSUE TITLE
Map/curate 344 EFO measurement branch terms to OBA traits

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#276]
- [x] Map EFO measurement branch terms to OBA traits
- [x] Create new OBA trait terms as needed

Related to
https://github.com/obophenotype/bio-attribute-ontology/issues/162#issuecomment-1658920829

**Comment by rays22** [comment]
- [ ] Map EFO measurement branch terms to OBA traits
- [ ] Create new OBA trait terms as needed

Related to
https://github.com/obophenotype/bio-attribute-ontology/issues/162#issuecomment-1658920829

**Comment by rays22** [comment]
Mapping table: https://docs.google.com/spreadsheets/d/1YXwgzdZ4dSxfDpipfjfxNsw3uJGB_wNsbxRHUwsgVdk/edit#gid=1050615924

**Comment by rays22** [comment]
* Examples of different ways of measuring the same trait, or different statistical attributes of a variable trait. 
 
id | label | entity | entity label | quality | quality label | location | location label | mapping predicate
-- | -- | -- | -- | -- | -- | -- | -- | --
EFO:0004528 | mean corpuscular hemoglobin concentration | CHEBI:35143 | hemoglobin | PATO:0000070 | amount | CL:0000232 | erythrocyte | skos:exactMatch
EFO:0009202 | Reticulocyte Mean Corpuscular Hemoglobin Measurement | CHEBI:35143 | hemoglobin | PATO:0000070 | amount | CL:0000558 | reticulocyte | skos:exactMatch
EFO:0009204 | Corpuscular Hemoglobin Concentration Distribution Width | CHEBI:35143 | hemoglobin | PATO:0001303 | variability | CL:0000232 | erythrocyte | skos:exactMatch
EFO:0009205 | Corpuscular Hemoglobin Content | CHEBI:35143 | hemoglobin | PATO:0000070 | amount | CL:0000232 | erythrocyte | skos:exactMatch
EFO:0009228 | Reticulocyte Corpuscular Hemoglobin Concentration Mean | CHEBI:35143 | hemoglobin | PATO:0000070 | amount | CL:0000558 | reticulocyte | skos:exactMatch
EFO:0009229 | Reticulocyte Corpuscular Hemoglobin Content | CHEBI:35143 | hemoglobin | PATO:0000070 | amount | CL:0000558 | reticulocyte | skos:exactMatch
EFO:0009230 | Reticulocyte Corpuscular Hemoglobin Distribution Width | CHEBI:35143 | hemoglobin | PATO:0001303 | variability | CL:0000558 | reticulocyte | skos:exactMatch
EFO:0009231 | Reticulocyte Hemoglobin Distribution Width | CHEBI:35143 | hemoglobin | PATO:0001303 | variability | CL:0000558 | reticulocyte | skos:exactMatch

**Comment by matentzn** [comment]
We are not creating trait terms for statistical measures I assume?

**Comment by matentzn** [comment]
Very good!

**Comment by rays22** [comment]
* Progress so far:

class to be defined | predicate | defined_class_name | entity | entity_name | attribute | attribute_name | location | location_name | exact_synonyms
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
EFO:0010759 | skos:exactMatch | male reproductive system attribute | UBERON:0000079 | male reproductive system | PATO:0000001 | quality | none | #N/A |  
EFO:0004464 | skos:exactMatch | brain attribute | UBERON:0000955 | brain | PATO:0000001 | quality | none | #N/A |  
EFO:0004550 | skos:exactMatch | amygdala reactivity attribute | GO:0050896 | response to stimulus | PATO:0000001 | quality | UBERON:0001876 | amygdala |  
EFO:0004782 | skos:exactMatch | behaviour attribute | GO:0007610 | behavior | PATO:0000001 | quality | none | #N/A |  
EFO:0007021 | skos:exactMatch | Lewy body attribute | GO:0097413 | Lewy body | PATO:0000001 | quality | none | #N/A |  
EFO:0007716 | skos:exactMatch | carotid artery attribute | UBERON:0005396 | carotid artery segment | PATO:0000001 | quality | none | #N/A |  
EFO:0007738 | skos:exactMatch | cingulate cortex attribute | UBERON:0003027 | cingulate cortex | PATO:0000001 | quality | none | #N/A |  
EFO:0007786 | skos:exactMatch | menstrual cycle attribute | GO:0044850 | menstrual cycle | PATO:0000001 | quality | none | #N/A |  
EFO:0008375 | skos:exactMatch | macula attribute | UBERON:0000054 | macula | PATO:0000001 | quality | none | #N/A |  
EFO:0008389 | skos:exactMatch | putamen attribute | UBERON:0001874 | putamen | PATO:0000001 | quality | none | #N/A |  
EFO:0008420 | skos:exactMatch | parietal cortex attribute | UBERON:0016530 | parietal cortex | PATO:0000001 | quality | none | #N/A |  
EFO:0010079 | skos:exactMatch | corneal endothelial cell attribute | CL:0000132 | corneal endothelial cell | PATO:0000001 | quality | none | #N/A |  
EFO:0010128 | skos:exactMatch | immunoglobulin isotype switching measurement | GO:0045190 | isotype switching | PATO:0001236 | process quality | none | #N/A |  
EFO:0007772 | skos:closeMatch | calcaneal bone quantitative ultrasound measurement | UBERON:0001450 | calcaneus | PATO:0000001 | quality | none | #N/A |  
EFO:0007822 | skos:exactMatch | hair colour measurement | UBERON:0001037 | strand of hair | PATO:0000014 | color | none | #N/A |  
EFO:0600084 | skos:exactMatch | bowel opening frequency | GO:0035882 | defecation rhythm | PATO:0000044 | frequency | none | #N/A |  
EFO:0007717 | skos:closeMatch | carotid artery attribute | UBERON:0005396 | carotid artery segment | PATO:0000051 | morphology | none | #N/A | carotid artery geometry attribute
EFO:0010972 | skos:exactMatch | blood phosphate attribute | CHEBI:26020 | phosphate | PATO:0000070 | amount | UBERON:0000178 | blood |  
EFO:0010914 | skos:exactMatch | fatty acid-binding protein level in adipocyte | PR:000025846 | fatty acid-binding protein | PATO:0000070 | amount | CL:0000136 | fat cell | fatty acid-binding protein, adipocyte attribute
EFO:0020373 | skos:exactMatch | fatty acid-binding protein level in heart | PR:000025846 | fatty acid-binding protein | PATO:0000070 | amount | UBERON:0000948 | heart | fatty acid-binding protein, heart attribute
EFO:0009250 | skos:exactMatch | Prorubricyte Count | CL:0000549 | basophilic erythroblast | PATO:0000070 | amount | none | #N/A | Prorubricyte Count
EFO:0009239 | skos:exactMatch | plasma cell count | CL:0000786 | plasma cell | PATO:0000070 | amount | none | #N/A | Mature Plasma Cell Count
EFO:0008301 | skos:exactMatch | toll-like receptor 4:Lymphocyte antigen 96 complex amount | PR:000036003 | LY96:TLR4 complex | PATO:0000070 | amount | UBERON:0001062 | anatomical entity | toll-like receptor 4:Lymphocyte antigen 96 complex attribute
EFO:0009187 | skos:broadMatch | immature platelet quantity | CL:0000233 | platelet | PATO:0000070 | amount | none | #N/A | immature platelet fraction
EFO:0009238 | skos:broadMatch | Immature Plasma Cell Count | CL:0000786 | plasma cell | PATO:0000070 | amount | none | #N/A |  
EFO:0009253 | skos:broadMatch | immature reticulocyte amount | CL:0000558 | reticulocyte | PATO:0000070 | amount | none | #N/A | Immature Reticulocyte Fraction attribute
EFO:0020318 | skos:exactMatch | dentin matrix acidic phosphoprotein 1 amount | PR:000006540 | dentin matrix acidic phosphoprotein 1 | PATO:0000070 | amount | UBERON:0001062 | anatomical entity | dentin matrix acidic phosphoprotein 1 attribute
EFO:0004308 | skos:exactMatch | leukocyte count | CL:0000738 | leukocyte | PATO:0000070 | amount | none | #N/A |  
EFO:0007988 | skos:exactMatch | myeloid white cell count | CL:0000766 | myeloid leukocyte | PATO:0000070 | amount | none | #N/A | myeloid white cell count
EFO:0004528 | skos:exactMatch | hemoglobin amount in erythrocyte | CHEBI:35143 | hemoglobin | PATO:0000070 | amount | CL:0000232 | erythrocyte | corpuscular hemoglobin amount
EFO:0009202 | skos:exactMatch | reticulocyte corpuscular hemoglobin quantity | CHEBI:35143 | hemoglobin | PATO:0000070 | amount | CL:0000558 | reticulocyte |  
EFO:0009204 | skos:exactMatch | corpuscular hemoglobin variability attribute | CHEBI:35143 | hemoglobin | PATO:0001303 | variability | CL:0000232 | erythrocyte |  
EFO:0009205 | skos:exactMatch | corpuscular hemoglobin content | CHEBI:35143 | hemoglobin | PATO:0000070 | amount | CL:0000232 | erythrocyte |  
EFO:0009228 | skos:exactMatch | reticulocyte corpuscular hemoglobin quantity | CHEBI:35143 | hemoglobin | PATO:0000070 | amount | CL:0000558 | reticulocyte |  
EFO:0009229 | skos:exactMatch | reticulocyte corpuscular hemoglobin content | CHEBI:35143 | hemoglobin | PATO:0000070 | amount | CL:0000558 | reticulocyte |  
EFO:0009230 | skos:exactMatch | reticulocyte corpuscular hemoglobin variability | CHEBI:35143 | hemoglobin | PATO:0001303 | variability | CL:0000558 | reticulocyte |  
EFO:0009231 | skos:exactMatch | Reticulocyte Hemoglobin Distribution Width | CHEBI:35143 | hemoglobin | PATO:0001303 | variability | CL:0000558 | reticulocyte | Reticulocyte Hemoglobin Distribution Width
EFO:0004532 | skos:exactMatch | serum gamma-glutamyl transferase level | PR:000001458 | glutathione hydrolase 1 proenzyme | PATO:0000070 | amount | UBERON:0001977 | blood serum |  
EFO:0004536 | skos:exactMatch | total blood protein mass | CHEBI:36080 | protein | PATO:0000125 | mass | UBERON:0000178 | blood | total blood protein amount
EFO:0004741 | skos:exactMatch | blood urea nitrogen level | CHEBI:16199 | urea | PATO:0000070 | amount | UBERON:0000178 | blood |  
EFO:0004749 | skos:exactMatch | C-C motif chemokine 2 level | PR:000002122 | C-C motif chemokine 2 | PATO:0000070 | amount | UBERON:0001062 | anatomical entity | CCL2 level
EFO:0004764 | skos:exactMatch | adipose tissue quantity | UBERON:0001013 | adipose tissue | PATO:0000070 | amount | none | #N/A |  
EFO:0004765 | skos:exactMatch | visceral adipose tissue quantity | UBERON:0035818 | visceral fat | PATO:0000070 | amount | none | #N/A |  
EFO:0004864 | skos:exactMatch | renal sinus adipose tissue quantity | UBERON:0001013 | adipose tissue | PATO:0000070 | amount | UBERON:0006171 | renal sinus |  
EFO:0005036 | skos:exactMatch | platelet quantity | CL:0000233 | platelet | PATO:0000070 | amount | none | #N/A |  
EFO:0005193 | skos:exactMatch | serum IgG glycosylation level | GO:0006487 | protein N-linked glycosylation | PATO:0001236 | process quality | GO:0071736 | IgG immunoglobulin complex, circulating |  
EFO:0005653 | skos:exactMatch | serum metabolite level | CHEBI:25212 | metabolite | PATO:0000070 | amount | UBERON:0001977 | blood serum |  
EFO:0005664 | skos:exactMatch | blood metabolite level | CHEBI:25212 | metabolite | PATO:0000070 | amount | UBERON:0000178 | blood |  
EFO:0005760 | skos:exactMatch | serum carcinoembryonic antigen level | PR:000001330 | carcinoembryonic antigen-related cell adhesion molecule 5 | PATO:0000070 | amount | UBERON:0001977 | blood serum |  
EFO:0006920 | skos:exactMatch | natriuretic peptides B level | PR:000011375 | natriuretic peptides B | PATO:0000070 | amount | UBERON:0001062 | anatomical entity | BNP quantity
EFO:0006959 | skos:exactMatch | gene methylation level | GO:0006306 | DNA methylation | PATO:0000070 | amount | UBERON:0001062 | anatomical entity |  
EFO:0007578 | skos:exactMatch | blood copper level | CHEBI:28694 | copper atom | PATO:0000070 | amount | UBERON:0000178 | blood |  
EFO:0007615 | skos:exactMatch | thrombus formation level | UBERON:0010210 | blood clot | PATO:0000070 | amount | none | #N/A |  
EFO:0007657 | skos:exactMatch | cerebrospinal fluid clusterin level | PR:000005615 | clusterin | PATO:0000070 | amount | UBERON:0001359 | cerebrospinal fluid |  
EFO:0007807 | skos:exactMatch | erythrocyte cadmium level | CHEBI:22977 | cadmium atom | PATO:0000070 | amount | CL:0000232 | erythrocyte |  
EFO:0007937 | skos:exactMatch | blood protein level | PR:000000001 | protein | PATO:0000070 | amount | UBERON:0000178 | blood |  
EFO:0007980 | skos:exactMatch | cerebral blood flow level | UBERON:0000178 | blood | PATO:0002243 | fluid flow rate | UBERON:0000955 | brain |  
EFO:0008142 | skos:exactMatch | granulocyte colony-stimulating factor level | PR:000005932 | granulocyte colony-stimulating factor | PATO:0000070 | amount | UBERON:0001062 | anatomical entity |
