### ISSUE TITLE
PR:000000001 and protein (CHEBI:36080) has cyclic dependency

### ISSUE THREAD

**Issue by gabbysantos** [obophenotype/bio-attribute-ontology#313]
Hi there, PR:000000001 and protein (CHEBI:36080) has cyclic dependency suggest removing the subclass relation. 

Thanks
Gabby

**Comment by matentzn** [comment]
Thank you for the report @gabbysantos - deeply appreciated.

There are 10 such cycles in OBA it seems:

1. GO:0000313 GO:0005840
2. GO:0099568 GO:0005737
3. CHEBI:18111 SO:0000252
4. CHEBI:36080 PR:000000001
5. GO:0005938 GO:0099738
6. CHEBI:33699 SO:0000234
7. GO:0090068 GO:0045787
8. GO:0010564 GO:0051726
9. GO:0045786 GO:0010948
10. GO:0005829 GO:0099522

These are all victims of an OBA preprocessing step which I am fixing:

1. GO:0099568 GO:0005737
2. GO:0005938 GO:0099738
3. GO:0000313 GO:0005840
4. GO:0005938 GO:0099738
5. GO:0010564 GO:0051726
6. GO:0045786 GO:0010948
7. GO:0005829 GO:0099522

These are asserted:

1. CHEBI:18111 SO:0000252
2. CHEBI:33699 SO:0000234
3. CHEBI:36080 PR:000000001

I will implement the following solution unless anyone screams:

1. for the asserted cases, I will remove the three SO terms and PRO terms after reasoning. The correct solution would be https://github.com/ontodev/robot/issues/1060 but I do not have time to deal with that right now
2. For the other cases I need to check something with the GO team.
