### ISSUE TITLE
epiphysis

### ISSUE THREAD

**Issue by megbalk** [obophenotype/bio-attribute-ontology#33]
#33 Is epiphysis (e.g., distal epiphysis of femur) considered an adult trait or a juvenile trait?
In terms of development, juveniles have an epiphyseal plate that is unfused until maturation. To refer to an epiphysis is to refer to a juvenile bone. 
At maturation, the epiphysEs fuse to to the diaphysis, and then is referred to as the ephipysEs of a bone for adults. 
Some clarification on life stage this term is referring to would be helpful.

**Comment by cmungall** [comment]
OBA uses Uberon as it's anatomical basis so we'll answer this on here: https://github.com/obophenotype/uberon/issues/1499

If there are nomenclature changes in Uberon this will be reflected in the corresponding trait term in OBA
