### ISSUE TITLE
Are OBA:0000036 body fluid levels really an anatomical structure size trait ? 

### ISSUE THREAD

**Issue by pgaudet** [obophenotype/bio-attribute-ontology#35]
id: OBA:0000036
name: body fluid levels

- is_a: OBA:VT0010454 ! organism trait
+ is_a: OBA:VT0100005 ! body size trait

In the new import into GO, this creates an inference 'regulation of body fluid levels SubClassOf regulation of anatomical structure size', which seems incorrect. 

Can you please check and edit ? 

Thanks, Pascale

**Comment by cmungall** [comment]
This arises from the fact that

 1. volume is-a size in PATO
 2. 'anatomical structure' is a very broad class, encompassing for example a particular portion of blood in an arbitrary segment of a blood vessel

Number 1 is being discussed here https://github.com/pato-ontology/pato/issues/246

Regarding 2, I think when GO talks of 'regulation of anatomical structure size' we are talking about more "discrete" anatomical structures. But maybe this is moot if 1 is resolved
