### ISSUE TITLE
missing version IRI

### ISSUE THREAD

**Issue by balhoff** [obophenotype/bio-attribute-ontology#38]
The OBA release doesn't state a version IRI.

**Comment by balhoff** [comment]
As of `http://purl.obolibrary.org/obo/oba/releases/2021-12-03/oba.owl` there is a version IRI, but it doesn't resolve.

**Comment by matentzn** [comment]
Fixed here: https://github.com/OBOFoundry/purl.obolibrary.org/pull/816/files


Thanks for chasing
