### ISSUE TITLE
size trait v bone size

### ISSUE THREAD

**Issue by megbalk** [obophenotype/bio-attribute-ontology#40]
I've seen both used, which is preferred?

**Comment by cmungall** [comment]
can you give an example?

**Comment by megbalk** [comment]
OBA:0002374 'radius bone size'
OBA_VT1000369 'femur size trait'

**Comment by matentzn** [comment]
@megbalk this is one of the key issues in our trait/measurement/phenotype meeting. You want to prefer 'radius bone size', mainly to punt on the question of trait vs biological attribute vs phenotypic characteristic.

**Comment by megbalk** [comment]
Should I change those that currently say "size trait" to "bone size" or make "bone size" (for those that only have "size trait") a subclass of "size trait" or do nothing?

**Comment by matentzn** [comment]
These seem to be on a different level of abstraction. Bone size trait is
the same as bone size! Size trait should not even exist. Does it?

**Comment by megbalk** [comment]
it does, it will say "femur size trait" (which maybe bone is implicit, but it's not explicitly written)

**Comment by cmungall** [comment]
Isn't this purely a terminological difference (arising from the fact that
one was seeded from VT). These should follow the same axiom pattern

**Comment by megbalk** [comment]
@cmungall I am reopening this issue because @helenamachado and I found this issue again, and have more questions. It seems "morphological trait" and "size" and "size trait" are all redundant. For example "morphological trait" is always parent to "size" or "size trait" without any other children. Size, to me, is not a great term and I'd prefer to get rid of it completely and put traits like length, width, circumference, etc. directly under "morphological trait". Is there a way I can start changing this in the ontology? So, in the screen shot I'm attaching, we think it makes more sense to be: "morphology trait" then "depth" and "width".
<img width="372" alt="Screen Shot 2022-01-19 at 10 33 26 AM" src="https://user-images.githubusercontent.com/6617332/150183841-5cc0faea-8384-408a-94bf-733780ad3eb6.png">

**Comment by cmungall** [comment]
but there are other morphologies other than size... e.g shape

also it looks like we are not running reduce on the final product

![image](https://user-images.githubusercontent.com/50745/150188075-f48154e1-2cb6-4066-8b91-bcf48c3822bf.png)

**Comment by matentzn** [comment]
We are running reduce: https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/ontology/oba.Makefile#L25

**Comment by megbalk** [comment]
What's reduce?

**Comment by matentzn** [comment]
A robot command, (mostly) irrelevant to this issue here.
