### ISSUE TITLE
skin mass axiomization

### ISSUE THREAD

**Issue by megbalk** [obophenotype/bio-attribute-ontology#41]
skin mass is currently axiomized as: mass and ('inheres in' some '**zone of skin**') 
I think it should be: mass and ('inheres in' some '**skin of body**')

**Comment by megbalk** [comment]
there is also skin of body size trait, so perhaps that is what skin mass should be nested under.

It currently isn't nested under any size traits.

**Comment by rays22** [comment]
[OBA:VT1000425 skin mass](https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBA_VT1000425) has a synonym **mass of zone of skin**, thus the
axiom is in agreement with the synonym:
* `Equivalent to:`
[mass](https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000125) and [characteristic of](https://www.ebi.ac.uk/ols/ontologies/oba/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000052) some [zone of skin](https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000014)

The difference between
* [UBERON:0000014 zone of skin](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000014&lang=en&viewMode=PreferredRoots&siblings=false) and
* [UBERON:0002097 skin of body](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002097)
is that the latter means the **entire skin**.

I would leave [OBA:VT1000425 skin mass](https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBA_VT1000425) as it is now.

If you wish, you can make a new OBA trait that uses [UBERON:0002097 skin of body](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002097) and name it `total mass of skin` or `total skin mass` to reflect the intended use case.

Maybe we should rename OBA:0002168 similarly:

```
2487:OBA:0002168                UBERON:0002097  skin of body    PATO:0000117    size
3935:OBA:0003618                UBERON:0000014  zone of skin    PATO:0000117    size

```


Please, note that the OBA hierarchy is driven by the source ontologies, i.e. UBERON and PATO in the current case.
[PATO:0000125 mass](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000125) is actually not a child of [PATO:0000117 size](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000117) for some reason, which explains why `mass` traits are not nested under `size` traits in OBA.
I see your point that one would expect `mass` to be related to `size`, but that issue needs to be raised in PATO.

**Comment by megbalk** [comment]
ok, I'll create a new issue to do this
