### ISSUE TITLE
Need replacement terms

### ISSUE THREAD

**Issue by matentzn** [obophenotype/bio-attribute-ontology#47]
These terms are used in OBA to define traits:

OBA:0003943 http://purl.obolibrary.org/obo/GO_0005605 morphology 
OBA:0004453 http://purl.obolibrary.org/obo/GO_0072642 rate 
OBA:0004454 http://purl.obolibrary.org/obo/GO_0035546 rate 
OBA:0004455 http://purl.obolibrary.org/obo/GO_0072643 rate 
OBA:0004465 http://purl.obolibrary.org/obo/GO_0050701 rate 
OBA:0004466 http://purl.obolibrary.org/obo/GO_0050703 rate 
OBA:0004467 http://purl.obolibrary.org/obo/GO_0050702 rate 
OBA:0004468 http://purl.obolibrary.org/obo/GO_0072608 rate 
OBA:0004469 http://purl.obolibrary.org/obo/GO_0072610 rate 
OBA:0004470 http://purl.obolibrary.org/obo/GO_0072611 rate 
OBA:0004471 http://purl.obolibrary.org/obo/GO_0072613 rate 
OBA:0004472 http://purl.obolibrary.org/obo/GO_0072614 rate 
OBA:0004473 http://purl.obolibrary.org/obo/GO_0072615 rate 
OBA:0004474 http://purl.obolibrary.org/obo/GO_0072616 rate 
OBA:0004475 http://purl.obolibrary.org/obo/GO_0070970 rate 
OBA:0004476 http://purl.obolibrary.org/obo/GO_0072621 rate 
OBA:0004477 http://purl.obolibrary.org/obo/GO_0072601 rate 
OBA:0004478 http://purl.obolibrary.org/obo/GO_0072602 rate 
OBA:0004479 http://purl.obolibrary.org/obo/GO_0072603 rate 
OBA:0004480 http://purl.obolibrary.org/obo/GO_0072604 rate 
OBA:0004481 http://purl.obolibrary.org/obo/GO_0072605 rate 
OBA:0004482 http://purl.obolibrary.org/obo/GO_0072607 rate 
OBA:0004597 http://purl.obolibrary.org/obo/GO_0072619 rate 
OBA:0005526 http://purl.obolibrary.org/obo/GO_0072606 rate 
OBA:0005767 http://purl.obolibrary.org/obo/GO_0072372 morphology 
OBA:0005768 http://purl.obolibrary.org/obo/GO_0031513 morphology 
OBA:0005773 http://purl.obolibrary.org/obo/GO_0072372 functionality 
OBA:0005774 http://purl.obolibrary.org/obo/GO_0031513 functionality 

I need replacements for these.. Blocking #43

**Comment by dosumis** [comment]
Can you just follow replaced_by? to find the replacement term?  First 3 I spot checked had a single replaced_by axioms pointing to a valid term.

**Comment by matentzn** [comment]
Yeah, you can follow these I assume. Never quite sure these are equivalence replacements. Could we have someone do this then?

**Comment by dosumis** [comment]
> Yeah, you can follow these I assume. Never quite sure these are equivalence replacements. 

We should have an automated pipeline for doing this, which generates reports of automated substitutions.  This could be done with SPARQL.  I'll write a ticket on ODK.  

> Could we have someone do this then?

@matentzn - I assume they need replacing src/patterns/data/default/entity_attribute.tsv on this branch.

@rays22  - Please make these mappings.  

For each term we need to look to see if there is a *single* replaced_by statement and use the term this points to and use this to replace the entry in the entity_attribute.tsv.

The cases I've looked at are all from merges, hence the lack of additional metadata on the deprecated terms.

e.g.: 
http://amigo.geneontology.org/amigo/term/GO:0072606
![image](https://user-images.githubusercontent.com/112839/143414979-5e339091-a048-4312-bb12-127d34975bba.png)

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0072606
![image](https://user-images.githubusercontent.com/112839/143415020-64d7025f-0352-4223-8c42-cd9a1b372827.png)

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0072606#term=history
![image](https://user-images.githubusercontent.com/112839/143415156-19b7e530-e604-4322-aa18-c93089834c72.png)

In other cases this will have been a genuine direct obsoletion by an editor. In this case you will see annotations on the old term (label, comments).  In these cases look out for the use of `consider` AP axioms + a comment on mapping.  These are for the rare case where some editor/curator input is expected in updating mappings.

The list is not huge, so it 's probably easiest just to do this set by hand, esp as this is easy to do by following the links above.

**Comment by matentzn** [comment]
All changes must be done against https://github.com/obophenotype/bio-attribute-ontology/pull/43

there is already a lot in there!

So @rays22, if you could make a PR against the ODK branch above, that would be great.

**Comment by matentzn** [comment]
And yes, there are only three files that need editing, all the TSV files in src/patterns/data/default

**Comment by rays22** [comment]
I am going to use the terms in the table below as replacements. The obsolete GO terms (e.g. containing `secretion` in the label) are typically narrow synonyms of the new (merged) GO terms (containing `production` in the label).


CURIE | # | GO CURIE | replacement | label
-- | -- | -- | -- | --
OBA:0003943 | 1 | GO:0005605 | GO:0005604 | basement membrane
OBA:0004453 | 2 | GO:0072642 | GO:0032607 | interferon-alpha production
OBA:0004454 | 3 | GO:0035546 | GO:0032608 | interferon-beta production
OBA:0004455 | 4 | GO:0072643 | GO:0032609 | interferon-gamma production
OBA:0004465 | 5 | GO:0050701 | GO:0032612 | interleukin-1 production
OBA:0004466 | 6 | GO:0050703 | GO:0032610 | interleukin-1 alpha production
OBA:0004467 | 7 | GO:0050702 | GO:0032611 | interleukin-1 beta production
OBA:0004468 | 8 | GO:0072608 | GO:0032613 | interleukin-10 production
OBA:0004469 | 9 | GO:0072610 | GO:0032615 | interleukin-12 production
OBA:0004470 | 10 | GO:0072611 | GO:0032616 | interleukin-13 production
OBA:0004471 | 11 | GO:0072613 | GO:0032618 | interleukin-15 production
OBA:0004472 | 12 | GO:0072614 | GO:0032619 | interleukin-16 production
OBA:0004473 | 13 | GO:0072615 | GO:0032620 | interleukin-17 production
OBA:0004474 | 14 | GO:0072616 | GO:0032621 | interleukin-18 production
OBA:0004475 | 15 | GO:0070970 | GO:0032623 | interleukin-2 production
OBA:0004476 | 16 | GO:0072621 | GO:0032627 | interleukin-23 production
OBA:0004477 | 17 | GO:0072601 | GO:0032632 | interleukin-3 production
OBA:0004478 | 18 | GO:0072602 | GO:0032633 | interleukin-4 production
OBA:0004479 | 19 | GO:0072603 | GO:0032634 | interleukin-5 production
OBA:0004480 | 20 | GO:0072604 | GO:0032635 | interleukin-6 production
OBA:0004481 | 21 | GO:0072605 | GO:0032636 | interleukin-7 production
OBA:0004482 | 22 | GO:0072607 | GO:0032638 | interleukin-9 production
OBA:0004597 | 23 | GO:0072619 | GO:0032625 | interleukin-21 production
OBA:0005526 | 24 | GO:0072606 | GO:0032637 | interleukin-8 production
OBA:0005767 | 25 | GO:0072372 | GO:0005929 | cilium
OBA:0005768 | 26 | GO:0031513 | GO:0097730 | non-motile cilium
OBA:0005773 | 27 | GO:0072372 | GO:0005929 | cilium
OBA:0005774 | 28 | GO:0031513 | GO:0097730 | non-motile cilium

**Comment by rays22** [comment]
> In other cases this will have been a genuine direct obsoletion by an editor. In this case you will see annotations on the old term (label, comments). In these cases look out for the use of `consider` AP axioms + a comment on mapping. These are for the rare case where some editor/curator input is expected in updating mappings.

All the obsoleted terms are from merges. As a result, the replacement terms have somewhat broader meaning than the originals.

**Comment by matentzn** [comment]
Thank you @rays22 looks ok to me

**Comment by dosumis** [comment]
> All the obsoleted terms are from merges. As a result, the replacement terms have somewhat broader meaning than the originals.

I think that's fine.  No existing usage will be wrong in that case.

**Comment by rays22** [comment]
This issue looks resolved to me. Please, re-open it if there is anything else remaining to do.
