### ISSUE TITLE
Fixing ROBOT report errors before merging ODK branch

### ISSUE THREAD

**Issue by matentzn** [obophenotype/bio-attribute-ontology#48]
@rays22 Could you try to fix the following robot report errors? I think they are only about 20 errors (not 100), they just keep repeating themselves. Here is what I think:

1. The same class or similar class has been added accidentally. If that is so, you can inspect them in the spreadsheet (also, check out oba and look at oba-edit.owl on the branch).
2. If a trait appears duplicated, you remove one of the two (favour removal of `OBA:...` classes over `OBA:VT...` classes). The one you remove, you add it to the src/templates/replaced.tsv table

Fix errors:

Level | Rule Name | Subject | Property | Value
| --- | ---- | ---- | ---- | ----- |
ERROR | duplicate_definition | vocalization behavior quality | definition | The quality of a vocalization behavior.
ERROR | duplicate_definition | vocalization trait | definition | The quality of a vocalization behavior.
ERROR | duplicate_definition | parental behavior quality | definition | The quality of a parental behavior.
ERROR | duplicate_definition | parental behavior trait | definition | The quality of a parental behavior.
ERROR | duplicate_definition | grooming behavior quality | definition | The quality of a grooming behavior.
ERROR | duplicate_definition | grooming behavior trait | definition | The quality of a grooming behavior.
ERROR | duplicate_definition | cilium morphology | definition | The morphology of a cilium.
ERROR | duplicate_definition | cilium morphology | definition | The morphology of a cilium.
ERROR | duplicate_definition | basement membrane morphology | definition | The morphology of a basement membrane.
ERROR | duplicate_definition | basement membrane morphology trait | definition | The morphology of a basement membrane.
ERROR | duplicate_definition | cilium functionality | definition | The functionality of a cilium.
ERROR | duplicate_definition | cilium functionality | definition | The functionality of a cilium.
ERROR | duplicate_definition | protein amount | definition | The amount of a protein.
ERROR | duplicate_definition | protein amount | definition | The amount of a protein.
ERROR | missing_label | OBA:0000001 | rdfs:label | 
ERROR | missing_label | OBA:0000037 | rdfs:label | 
ERROR | missing_label | OBA:0000039 | rdfs:label | 
ERROR | missing_label | OBA:0000069 | rdfs:label | 
ERROR | missing_label | OBA:0000085 | rdfs:label | 
ERROR | missing_label | OBA:0000089 | rdfs:label | 
ERROR | missing_label | OBA:0000121 | rdfs:label | 
ERROR | missing_label | OBA:0000134 | rdfs:label | 
ERROR | missing_label | OBA:0000136 | rdfs:label | 
ERROR | missing_label | OBA:0000140 | rdfs:label | 
ERROR | missing_label | OBA:0000141 | rdfs:label | 
ERROR | missing_label | OBA:0000181 | rdfs:label | 
ERROR | missing_label | OBA:0001001 | rdfs:label | 
ERROR | misused_obsolete_label | obsolete heart contraction rate | rdfs:label | obsolete heart contraction rate
ERROR | misused_obsolete_label | obsolete death onset quality | rdfs:label | obsolete death onset quality
ERROR | misused_obsolete_label | obsolete cell functionality | rdfs:label | obsolete cell functionality
ERROR | misused_obsolete_label | obsolete cell nucleate quality | rdfs:label | obsolete cell nucleate quality
ERROR | misused_obsolete_label | obsolete cell ploidy | rdfs:label | obsolete cell ploidy
ERROR | misused_obsolete_label | obsolete podocyte foot process morphology | rdfs:label | obsolete podocyte foot process morphology
ERROR | misused_obsolete_label | obsolete podocyte foot process amount | rdfs:label | obsolete podocyte foot process amount
ERROR | misused_obsolete_label | obsolete magnocellular neurosecretory cell morphology | rdfs:label | obsolete magnocellular neurosecretory cell morphology
ERROR | misused_obsolete_label | obsolete magnocellular neurosecretory cell altered number of | rdfs:label | obsolete magnocellular neurosecretory cell altered number of
ERROR | misused_obsolete_label | obsolete respiratory system quality | rdfs:label | obsolete respiratory system quality
ERROR | misused_obsolete_label | obsolete reproductive system quality | rdfs:label | obsolete reproductive system quality
ERROR | misused_obsolete_label | obsolete nervous system quality | rdfs:label | obsolete nervous system quality
ERROR | misused_obsolete_label | obsolete glial cell (sensu Vertebrata) quality | rdfs:label | obsolete glial cell (sensu Vertebrata) quality
ERROR | misused_obsolete_label | obsolete cell morphology | rdfs:label | obsolete cell morphology
ERROR | misused_obsolete_label | obsolete paw/hand/foot/hoof morphology trait | rdfs:label | obsolete paw/hand/foot/hoof morphology trait
ERROR | duplicate_label | thymus mass | rdfs:label | thymus mass
ERROR | duplicate_label | thymus mass | rdfs:label | thymus mass
ERROR | duplicate_label | spleen mass | rdfs:label | spleen mass
ERROR | duplicate_label | spleen mass | rdfs:label | spleen mass
ERROR | duplicate_label | protein amount | rdfs:label | protein amount
ERROR | duplicate_label | protein amount | rdfs:label | protein amount
ERROR | duplicate_label | placenta mass | rdfs:label | placenta mass
ERROR | duplicate_label | placenta mass | rdfs:label | placenta mass
ERROR | duplicate_label | ovary mass | rdfs:label | ovary mass
ERROR | duplicate_label | ovary mass | rdfs:label | ovary mass
ERROR | duplicate_label | lung mass | rdfs:label | lung mass
ERROR | duplicate_label | lung mass | rdfs:label | lung mass
ERROR | duplicate_label | liver mass | rdfs:label | liver mass
ERROR | duplicate_label | liver mass | rdfs:label | liver mass
ERROR | duplicate_label | kidney mass | rdfs:label | kidney mass
ERROR | duplicate_label | kidney mass | rdfs:label | kidney mass
ERROR | duplicate_label | heart mass | rdfs:label | heart mass
ERROR | duplicate_label | heart mass | rdfs:label | heart mass
ERROR | duplicate_label | cilium morphology | rdfs:label | cilium morphology
ERROR | duplicate_label | cilium morphology | rdfs:label | cilium morphology
ERROR | duplicate_label | cilium functionality | rdfs:label | cilium functionality
ERROR | duplicate_label | cilium functionality | rdfs:label | cilium functionality
ERROR | duplicate_label | brain mass | rdfs:label | brain mass
ERROR | duplicate_label | brain mass | rdfs:label | brain mass
ERROR | duplicate_label | aorta mass | rdfs:label | aorta mass
ERROR | duplicate_label | aorta mass | rdfs:label | aorta mass
ERROR | duplicate_label | abdominal fat pad mass | rdfs:label | abdominal fat pad mass
ERROR | duplicate_label | abdominal fat pad mass | rdfs:label | abdominal fat pad mass
WARN | duplicate_exact_synonym | vocalization behavior quality | has_exact_synonym | quality of vocalization behavior
WARN | duplicate_exact_synonym | vocalization trait | has_exact_synonym | quality of vocalization behavior
WARN | duplicate_exact_synonym | parental behavior quality | has_exact_synonym | quality of parental behavior
WARN | duplicate_exact_synonym | parental behavior trait | has_exact_synonym | quality of parental behavior
WARN | duplicate_exact_synonym | grooming behavior quality | has_exact_synonym | quality of grooming behavior
WARN | duplicate_exact_synonym | grooming behavior trait | has_exact_synonym | quality of grooming behavior
WARN | duplicate_exact_synonym | cilium morphology | has_exact_synonym | morphology of cilium
WARN | duplicate_exact_synonym | cilium morphology | has_exact_synonym | morphology of cilium
WARN | duplicate_exact_synonym | basement membrane morphology | has_exact_synonym | morphology of basement membrane
WARN | duplicate_exact_synonym | basement membrane morphology trait | has_exact_synonym | morphology of basement membrane
WARN | duplicate_exact_synonym | cilium functionality | has_exact_synonym | functionality of cilium
WARN | duplicate_exact_synonym | cilium functionality | has_exact_synonym | functionality of cilium
WARN | duplicate_exact_synonym | protein amount | has_exact_synonym | amount of protein
WARN | duplicate_exact_synonym | protein amount | has_exact_synonym | amount of protein
WARN | missing_definition | OBA:0000001 | definition | 
WARN | missing_definition | OBA:0000037 | definition | 
WARN | missing_definition | OBA:0000039 | definition | 
WARN | missing_definition | OBA:0000069 | definition | 
WARN | missing_definition | obsolete heart contraction rate | definition | 
WARN | missing_definition | OBA:0000085 | definition | 
WARN | missing_definition | OBA:0000089 | definition | 
WARN | missing_definition | OBA:0000121 | definition | 
WARN | missing_definition | OBA:0000134 | definition | 
WARN | missing_definition | OBA:0000136 | definition | 
WARN | missing_definition | OBA:0000140 | definition | 
WARN | missing_definition | OBA:0000141 | definition | 
WARN | missing_definition | OBA:0000181 | definition | 
WARN | missing_definition | OBA:0001001 | definition |

**Comment by dosumis** [comment]
@matentzn  - looks like most of these are imports.  Can we turn strict SPARQL checks off for imported terms?  There's no accounting for what minor checks might fail in an ontology we import from.

**Comment by matentzn** [comment]
Which one of these are imports? I only pasted those errors that appear to relate directly to OBA!

**Comment by dosumis** [comment]
Sorry - misunderstood labels.

Note - looks like more obsolete terms coming through 

ERROR | misused_obsolete_label | obsolete cell ploidy | rdfs:label | obsolete cell ploidy
-- | -- | -- | -- | --

**Comment by matentzn** [comment]
Yes exactly.. My previous strategy to identify these by eye, missed these.

**Comment by matentzn** [comment]
@rays22 Let me know when you are done with this, so I can proceed to merge :) Thank yoU!

**Comment by rays22** [comment]
@matentzn ,
I have pushed a commit with a new `src/templates/replaced.tsv` that tries to fix the errors. Does it look OK?
I was not sure how to deal with the `missing_label` errors. My plan is to add back the missing labels.
I am also trying to obsolete two terms without any replacement terms, it that is OK.

```
Ontology ID	Type	Label	Obsolete	Replacement Term
ID	TYPE	A rdfs:label	AT owl:deprecated^^xsd:boolean	AI IAO:0100001
http://purl.obolibrary.org/obo/OBA_0002455	owl:Class	obsolete death onset quality	TRUE
http://purl.obolibrary.org/obo/OBA_1000873	owl:Class	obsolete glial cell (sensu Vertebrata) quality	TRUE
```

**Comment by rays22** [comment]
### Update and remaining tasks
#### Fixed:
- [x] obsolete fillers (`misused_obsolete_label`) from external ontologies in
    `.../patterns/data/default/attribute_location.tsv, .../patterns/data/default/entity_attribute.tsv, .../patterns/data/default/entity_attribute_location.tsv`
- [x] `duplicate_definition` errors by using `...src/templates/replaced.tsv`

* * * * * * * * * * * * * * * * * * *
#### Remaining tasks:
- [ ] fix `duplicate_label` errors
- [ ] fix `missing label` errors
