### ISSUE TITLE
Add age of onset (of disease) terms

### ISSUE THREAD

**Issue by dosumis** [obophenotype/bio-attribute-ontology#49]
The GWAS catalog needs terms for age of onset of disease.  We propose to use this pattern: 

<https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/dosdp-patterns/disease_onset.yaml>

The 'onset' term comes from the clinical course sub-ontogy in HP (HP:0003674):

![image](https://user-images.githubusercontent.com/112839/144617779-e3e6d783-d2e7-4555-b72c-77c772039298.png)

I think this is reasonable, even if it does not fit with our usual use of PATO in the Q slot + this being AFAIK the first use of Mondo in the E slot.

TODO: 
 - Populate table with terms needed by GWAS.  This requires some back and forth with GWAS (Eliot).
    -  Note - table is now in a [google sheet](https://docs.google.com/spreadsheets/d/1UiCa1XjLy1LAz-mnGuplb754DqzJjO9YlZ6eeS19uKY/edit#gid=1204072197) @matentzn - does this still need to be activated.   

CC @cmungall

**Comment by dosumis** [comment]
Update: 

Table has been updated with Mondo terms (see below).  There are a few blanks. The table will EFO/OBA/HP mappings below should help with either mapping to an existing Mondo term or requesting a new one.  Double Mondo ID -> 2 rows.  


disease | disease label | EFO/HP/Orphanet term
-- | -- | --
MONDO:0004975 | Alzheimer's disease | EFO:0000249
MONDO:0004979 | asthma | EFO:0000270
MONDO:0004986 | bladder carcinoma | EFO:0000292
  | cardiac arrhythmia | EFO:0004269
MONDO:0005129 | cataract | EFO:0001059
  | coronary atherosclerosis measurement | EFO:0007938
  | Hernia of the abdominal wall | HP:0004299
MONDO:0021187 | hyperlipidemia | EFO:0003774
MONDO:0005178 | osteoarthritis | EFO:0002506
MONDO:0005180 | Parkinson's disease | EFO:0002508
MONDO:0001134 | primary hypertension | EFO:1002032
MONDO:0005090 | schizophrenia | EFO:0000692
MONDO:0005147 | type I diabetes mellitus | EFO:0001359
MONDO:0005148 | type II diabetes mellitus | EFO:0001360
  | Age-related cataract | HP:0011141
MONDO:0005405 | childhood onset asthma | EFO:0004591
MONDO:0007079 | alcohol dependence | EFO:0003829
MONDO:0005271 | allergy | EFO:0003785
MONDO:0004976 | amyotrophic lateral sclerosis | EFO:0000253
MONDO:0004985 | psychotic symptoms, bipolar disorder | EFO:0005940, EFO:0000289
MONDO:0000327 | Buruli Ulcer | EFO:1001281
  | Cannabis use | EFO:0007585
MONDO:0017276 | Frontotemporal dementia | Orphanet:282
  | glioblastoma multiforme | EFO:0000519
MONDO:0007739 | Huntington disease | Orphanet:399
  | Machado-Joseph disease | MONDO:0007182
MONDO:0005277 | migraine disorder | EFO:0003821
MONDO:0005475 | migraine with aura | EFO:0005295
MONDO:0011847 | migraine without aura | EFO:0005296
MONDO:0005301 | multiple sclerosis | EFO:0003885
  | Myopia | MONDO:0001384
MONDO:0001384, MONDO:0004892 | Myopia, refractive error measurement | MONDO:0001384, EFO:0007814
MONDO:0016158 | narcolepsy with cataplexy | EFO:0000614

(Note - column can be retrieved from sheet history if needed for other purposes).

Work to do with EFO:

1.  Update EFO IDs to Mondo for these cases (also investigate updating others) https://github.com/EBISPOT/efo/issues/1381
2. Update EFO to allow dynamic import of OBA  https://github.com/EBISPOT/efo/issues/1382

The sheet is not yet wired up to the repo.  @matentzn

**Comment by matentzn** [comment]
@rays22 can do it when its ready! Just put it in the src/pattern/data/default directory, with the same name as the pattern.

**Comment by dosumis** [comment]
@kallia-p to double check that IDs in sheet are the correct Mondo IDs for these terms (mappings came from xrefs in EFO, which can become stale). 

Terms without Mondo IDs (also see table above for mappings to HPO and other sources):

iri | iri label | disease | disease label
-- | -- | -- | --
OBA:2001003 |   |   | cardiac arrhythmia
OBA:2001005 |   |   | coronary atherosclerosis measurement
OBA:2001006 |   |   | Hernia of the abdominal wall
OBA:2001014 |   |   | Age-related cataract
OBA:2001021 |   |   | Cannabis use
OBA:2001023 |   |   | glioblastoma multiforme
OBA:2001025 |   |   | Machado-Joseph disease

For these - request Mondo terms if possible - discuss with Mondo where HPO.  Discuss what's left with wider Monarch group.

**Comment by kallia-p** [comment]
@dosumis @rays22 
The Mondo IDs in the first table which came from xref mappings in EFO are correct. There are some variations in nomenclature between EFO and Mondo for example:

allergic disease (Mondo) vs. allergy (EFO)
essential hypertension vs. primary hypertension 
migraine without aura, susceptibility to, 4 vs. migraine without aura 
refractive error vs. refractive error measurement
narcolepsy-cataplexy syndrome vs. narcolepsy with cataplexy

These appear to be the same thing, care may need to be taken when converting disease measurements to disease only as sometimes the GWAS catalog may have requested a measurement term that is a biomarker for a disease and not the actual trait that has been measured (perhaps you could check with the GWAS catalog for these terms).

In the sheet you could also add the Mondo term glioblastoma MONDO:0018177 next to glioblastoma multiforme EFO:0000519. The definitions in Mondo and EFO are exactly the same.

In the sheet you could also add the Mondo term for Machado-Joseph disease MONDO:0007182 this is missing from the first table above.

**Comment by dosumis** [comment]
Just copy current spreadsheet to tsv in patterns/data/default.  Change headers to DOSDP standard.

**Comment by rays22** [comment]
I have copied [this table](https://docs.google.com/spreadsheets/d/1UiCa1XjLy1LAz-mnGuplb754DqzJjO9YlZ6eeS19uKY/edit#gid=1204072197) as a `tsv` to  `src/patterns/data/default`.
See [PR#62](https://github.com/obophenotype/bio-attribute-ontology/pull/62)
