### ISSUE TITLE
Term Genie for OBA

### ISSUE THREAD

**Issue by dosumis** [obophenotype/bio-attribute-ontology#5]
Wondering whether it is worth having a TG for generating new OBA terms for qualities that are 'attributes of' some specified anatomical structure, cell or cell component type.

BTW - doesn't this 'attribute of' pattern clash with the PATO inheres_in pattern?

**Comment by cmungall** [comment]
Already exists, http://oba.termgenie.org

The attribute-of pattern was chosen for two reasons

 * Retrospectively axiomatizing an ontology like TO or VT using a strong pattern like Q-in-E can lead to isa-poisoning
 * We can insulate from poisoning by wrapping each expression, e.g. has-part some (Q in some E), but this requires an ugly hack to stay in obo

However, TO has recently improved a lot. They no longer isa-overload, so we can safely apply a strong axiomatization without fear of poisoning. I think we're ready to refactor OBA. Stay tuned...

**Comment by dosumis** [comment]
Need permissions:

"Could not commit, the user is not authorized to execute a commit."

**Comment by cmungall** [comment]
Big refactor happening on a branch now, see https://github.com/obophenotype/bio-attribute-ontology/milestones/OBA%20refactor

**Comment by matentzn** [comment]
Closing because 100 years old and no serious plans towards this.
