### ISSUE TITLE
Build SSSOM files for mapping OBA terms to EFO measurement terms

### ISSUE THREAD

**Issue by dosumis** [obophenotype/bio-attribute-ontology#51]
Some limited work on this started here: https://docs.google.com/spreadsheets/d/13qh7dLE38vMyz91oRqj6GzKjFohNazNKAJxKG6Plw1o/edit#gid=1454298570

**Comment by matentzn** [comment]
Please just keep working on the SSSOM file in the google sheet until further notice - unfortunately I can only start dealing with this properly when I am back in February.

**Comment by dosumis** [comment]
Ray will work on converting to Robot templates

**Comment by matentzn** [comment]
We have SSSOM converters to turn mapping files into OWL.. No need to convert to ROBOT templates first.

**Comment by dosumis** [comment]
Sorry - wrong ticket - wrongly thought this was OBA patterns.

**Comment by dosumis** [comment]
We can work on some basic SSSOM files in your absence though.

**Comment by matentzn** [comment]
Suggestion:

- ROBOT query on OBA that prunes away "trait" and other fluffy terms from the label
- ROBOT query onf EFO that prunes away "trait" "measurement" and other fluffy terms from the label
- Create the two csv files like:

| id | label |
| --- | --- |
| EFO:00001 | bone length |
| EFO:00002 | bmi 

- See what how many terms match this way.
- Other than that we need some kind of manual process for curating this mapping
-
