### ISSUE TITLE
Add some new qualities

### ISSUE THREAD

**Issue by matentzn** [obophenotype/bio-attribute-ontology#52]
Add terms 

In 2018, @diatomsRcool started adding these:

2a1f349b-77d6-424b-8fff-a4f37ae54941,head width,PATO:0000921,width,UBERON:0000033,head
b948f71a-e90b-4b9f-b423-f2b1de402742,metafemur length,PATO:0000122,length,HAO:0001140,metafemur
b1990c0f-0437-42e1-98f5-1b47a4387e8a,beak length,PATO:0000122,length,UBERON:0005094,beak
f7e2a5e5-aab3-4cf4-b66e-df6cc883a9f6,cell length,PATO:0000122,length,GO:0005623,cell
4d6b5610-d7c6-4999-bcac-b83bf98d92b4,cell width,PATO:0000921,width,GO:0005623,cell
5c720f5c-61d7-4702-b133-86715dab7aae,fore wing length,PATO:0000122,length,HAO:0000351,fore wing
db2376a8-e854-4da9-81e3-cd9794b889c4,hind wing length,PATO:0000122,length,HAO:0000400,hind wing
f611d111-b792-4128-aa6f-aae2b766ab3d,seed volume,PATO:0000918,volume,PO:0009010,seed
f53b7788-ffa5-4fd1-b97e-e4da787ccf24,testis position,PATO:0000140,position,UBERON:0000473,testis
7f49497f-b27b-47a5-89b2-78aa636fc151,shelled egg length,PATO:0000122,length,UBERON:0007379,shelled egg
4001ad0f-2747-4e06-b95e-f1a22da090b9,shelled egg width,PATO:0000921,width,UBERON:0007379,shelled egg

can we please add them to entity_attribute.tsv (give them proper ids as well)?

Thank you. 

Here is the OLD pr I just closed:
https://github.com/obophenotype/bio-attribute-ontology/pull/24

**Comment by rays22** [comment]
* UBERON has a declared [focus on vertebrates.](https://obophenotype.github.io/uberon/about/) HAO terms do not really fit that scope (Hymenoptera are insects, not vertebrates).
I have removed the Hymenoptera anatomy-related classes for now:
HAO:0001140	metafemur
HAO:0000351	fore wing
HAO:0000400	hind wing

* GO:0005623	cell is *obsolete*. I have replaced it with
CL:0000003	native cell

Please, reopen this ticket if anything is missing.
