### ISSUE TITLE
Create a new DOSDP pattern to generate 'trait in response to X' names

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#53]
Create a new DOSDP pattern in order to generate `trait in response to X` names as discussed at the [2021-12-08 EFO-GWAS meeting.](https://docs.google.com/document/d/11O6nOYzVNiccu3yKMKuaq_GzhHnazIPhhl9qpFLT0JM/edit?disco=AAAATBV3Alk)
General agreement on `trait in response to X` and children will be adverse/therapeutic trait in response to terms.

**Comment by dosumis** [comment]
First step - make 'trait in response to chemical stimulus'. (maybe 'response to chemical stimulus (trait)'.  This will take a chemical (CHEBI molecular entity) as an arg.  Logical def pattern to use:

'process quality' and characteristic_of* some (response to stimulus and has_input some $chemical)

* might still be 'inheres in' on OBA.

Populate a TSV using: https://docs.google.com/spreadsheets/d/13qh7dLE38vMyz91oRqj6GzKjFohNazNKAJxKG6Plw1o/edit#gid=0

**Comment by dosumis** [comment]
Second step:  Classification by role.  This should probably go in EFO (TBD).

We need:
1. A classification of chemicals by their role.  We have this implicitly in the column 'EFO_nearest_parent_label'.  Some of this should already be in  CHEBI - but if not we need to work on an alternative - or fold the roles directly into a DOSDP pattern on EFO or OBA.

**Comment by dosumis** [comment]
What's left to do on this?  Are there any blockers?

**Comment by dosumis** [comment]
Ping

**Comment by rays22** [comment]
> What's left to do on this? Are there any blockers?

I am having problems with the filler tsv causing QC errors:
https://github.com/obophenotype/bio-attribute-ontology/pull/64#issuecomment-1108809874

**Comment by rays22** [comment]
Remaining task:
- [ ] Add variables for `Contributors` to the yaml pattern template.
    - Use a data_list_var + annotation axiom that references it.
- [ ] Check and make sure that all the filler tsv fields work as intended.
