### ISSUE TITLE
length v width

### ISSUE THREAD

**Issue by megbalk** [obophenotype/bio-attribute-ontology#61]
Is it preferable to use length and specify the axis over width? 
@helenamachado and I are making size terms and find width as a concept confusing.

**Comment by matentzn** [comment]
As per uPheno long standing discussion, YES. Avoid width as much as possible in favour of length of axis

**Comment by megbalk** [comment]
should we make length the parent term, then specify length + axis to specify which direction the trait is referring to? (e.g., snout length is parent to snout length anterior-posterior [which would traditionally just be snout length] and snout length medial-lateral [which would traditionally be snout width])? @helenamachado

**Comment by rays22** [comment]
In case it helps, the PATO definitions of length and width are
* [length:](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000122)
A 1-D extent quality which is equal to the distance between two points.
* [width:](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000921)
A 1-D extent quality which is equal to the distance from one side of an object to another side which is opposite.



You may want to consider a pattern
- length PATO:0000122
- anatomical entity 1 from UBERON
- appropriate terms from the Biological Spatial Ontology for [axis and/or direction](https://www.ebi.ac.uk/ols/search?q=axis&ontology=bspo)
- anatomical entity 2 from UBERON

Sorry if I misunderstood your question.

**Comment by megbalk** [comment]
I thought we were to avoid using the term "width"? If so, how should we start replacing width and how do we want the length nesting to be? E.g., "length AP", "length ML", and "length PD" with synonyms "depth", "breadth", and "length of major axis"?

**Comment by megbalk** [comment]
we decided that we will keep terms like "depth" and "width", but will logically define them using length + axes.
we will put synonyms of length + axes (e.g., humerus breadth = humerus length ML).
we also decided that "depth" and "breadth" are not subclasses of "width". 

@helenamachado
