### ISSUE TITLE
new term label for width and depth 

### ISSUE THREAD

**Issue by helenamachado** [obophenotype/bio-attribute-ontology#68]
For new term requests, please provide the following information:

## Preferred term label

orbit length ML and orbit length DV

## Synonyms

orbit width and orbit depth

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/oba)

## Attribution

https://orcid.org/0000-0001-8415-4848

**Comment by megbalk** [comment]
we decided to leave "width" and "depth" as terms, and will suggest synonyms with axes.

@helenamachado
