### ISSUE TITLE
Add an OBA VT mapping to OBA

### ISSUE THREAD

**Issue by matentzn** [obophenotype/bio-attribute-ontology#72]
- [x] Write a SPARQL CONSTRUCT query that matches all class that are migrated from OBA

```
OBA:VT0005416
```

with an explicit OBA xref:

```
OBA:VT0005416 skos:exactMatch VT:0005416
```

- [ ] Create a component that is generated by running that SPARQL query (and is imported into SRC).That component should depend on `../patterns/definitions.owl`

- [x] Write the same query as a SPARQL SELECT query to make a table and email it to @obwalton

**Comment by rays22** [comment]
> * [ ]  Write the same query as a SPARQL SELECT query to make a table and email it to @obwalton

@matentzn ,
I have a table with *1969* lines of `OBA - VT` pairs.
Which format shall I send it from the two versions below (or something else)?
* version 1 sample

OBA | VT
-- | --
OBA:VT0000000 | VT:0000000
OBA:VT0000002 | VT:0000002
OBA:VT0000003 | VT:0000003
OBA:VT0000005 | VT:0000005
OBA:VT0000006 | VT:0000006
OBA:VT0000010 | VT:0000010
OBA:VT0000012 | VT:0000012
OBA:VT0000013 | VT:0000013


* version 2 sample

OBA | RELATIONSHIP | VT | LABEL
-- | -- | -- | --
OBA:VT0000000 | skos:exactMatch | VT:0000000 | mammary gland secreted fluid morphology trait
OBA:VT0000002 | skos:exactMatch | VT:0000002 | head size trait
OBA:VT0000003 | skos:exactMatch | VT:0000003 | adipose morphology trait
OBA:VT0000005 | skos:exactMatch | VT:0000005 | right atrium size trait
OBA:VT0000006 | skos:exactMatch | VT:0000006 | esophagus size trait
OBA:VT0000010 | skos:exactMatch | VT:0000010 | abdominal fat pad morphology trait
OBA:VT0000012 | skos:exactMatch | VT:0000012 | left atrium size trait
OBA:VT0000013 | skos:exactMatch | VT:0000013 | adipose distribution trait
OBA:VT0000017 | skos:exactMatch | VT:0000017 | outer ear size trait
OBA:VT0000018 | skos:exactMatch | VT:0000018 | ventricle membranous septum morphology trait

**Comment by obwalton** [comment]
> > * [ ]   Write the same query as a SPARQL SELECT query to make a table and email it to @obwalton
> 
> @matentzn , I have a table with _1969_ lines of `OBA - VT` pairs. Which format shall I send it from the two versions below (or something else)?
> 
> * version 1 sample
> 
> OBA	VT
> OBA:VT0000000	VT:0000000
> OBA:VT0000002	VT:0000002
> OBA:VT0000003	VT:0000003
> OBA:VT0000005	VT:0000005
> OBA:VT0000006	VT:0000006
> OBA:VT0000010	VT:0000010
> OBA:VT0000012	VT:0000012
> OBA:VT0000013	VT:0000013
> * version 2 sample
> 
> OBA	RELATIONSHIP	VT	LABEL
> OBA:VT0000000	skos:exactMatch	VT:0000000	mammary gland secreted fluid morphology trait
> OBA:VT0000002	skos:exactMatch	VT:0000002	head size trait
> OBA:VT0000003	skos:exactMatch	VT:0000003	adipose morphology trait
> OBA:VT0000005	skos:exactMatch	VT:0000005	right atrium size trait
> OBA:VT0000006	skos:exactMatch	VT:0000006	esophagus size trait
> OBA:VT0000010	skos:exactMatch	VT:0000010	abdominal fat pad morphology trait
> OBA:VT0000012	skos:exactMatch	VT:0000012	left atrium size trait
> OBA:VT0000013	skos:exactMatch	VT:0000013	adipose distribution trait
> OBA:VT0000017	skos:exactMatch	VT:0000017	outer ear size trait
> OBA:VT0000018	skos:exactMatch	VT:0000018	ventricle membranous septum morphology trait

If you are asking me, from a mouse phenome database perspective, I think we'd be interested in the relationship as well.  Unless they are always "exactMatch", in which case the first format is fine.

**Comment by matentzn** [comment]
Commit the TSV file (either one is fine for now) as src/ontology/mappings/oba-vt.tsv. Next step is for @obwalton to compare that table with all entries in phenome db and tell us which VT identifiers used by phenome db he did not find in that table.

**Comment by rays22** [comment]
A `SPARQL construct` prototype is here: <https://api.triplydb.com/s/KxzBhKMxx>.

**Comment by matentzn** [comment]
Here is an example on how to do it:

https://github.com/obophenotype/upheno-dev/blob/master/src/ontology/upheno.Makefile#L222

Do it exactly like this. The associated sparql query also formats the mapping nicely like SSSOM!

**Comment by matentzn** [comment]
Lets call this done and add more specialised issues at a later stage.

https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/mappings/oba-vt.sssom.tsv
