### ISSUE TITLE
Fix chemical stimulus trait pattern issues

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#87]
List of tasks:
- [x] Remove the [CHEBI:50906 role](https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_50906) classes from filler table [`response_to_chemical_stimulus_trait.tsv`](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/data/default/response_to_chemical_stimulus_trait.tsv).
- [x] Replace some of the chemical entities in [`response_to_chemical_stimulus_trait.tsv`](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/data/default/response_to_chemical_stimulus_trait.tsv) with chemical entities that are better matched to the GO response terms.
    - CHEBI:30879	alcohol --> CHEBI:16236	ethanol
- [x] Add new response to stimulus by role of chemical template and filler table. Use the existing OBA classes that are removed from the `response to chemical stimulus by chemical entity` template.
- [x] Add variables for `Contributors` to the yaml pattern template.
    - Use a data_list_var + annotation axiom that references it.
    - Use `dcterms:contributor`.
- [x] Check and make sure that all the filler tsv fields (i.e. contributors) work as intended.

See also related issue: <https://github.com/obophenotype/bio-attribute-ontology/issues/53#issuecomment-1111239926_>

**Comment by rays22** [comment]
I can only 1 or 0 `created_by` annotations, because
* [created_by](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html)
    Cardinality: *zero or one*.

**Comment by matentzn** [comment]
Lets not use created_by.. ever. dcterms:contributor everywhere!

**Comment by rays22** [comment]
OK, I'll make a note of that.

> * Use a data_list_var + annotation axiom that references it.

It seems to me that only the DOS-DP OBO fields work with `data_list_vars`. Adding a list of `dcterms:contributor` annotations using `data_list_vars` did NOT work for me when I checked the generated owl axioms in a newly generated `definitions.owl`.
