### ISSUE TITLE
Specify preferred roots for OBA on OLS

### ISSUE THREAD

**Issue by dosumis** [obophenotype/bio-attribute-ontology#88]
Background: 
   - Specification is provided to OLS as part of config in order to limit root terms displayed. e.g CL has root term "cell". Without this, ontologies can become very messy to browse from top.  Here's OBA right now:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/112839/166672770-fceef499-688d-48ba-972b-e731bfc7ce59.png">

I think this term might be sufficient, but check if all terms with Trait in name are under this:
 
http://purl.obolibrary.org/obo/OBA_0000001 ('biological attribute')

**Comment by rays22** [comment]
1. I have found *1640* OBA terms with `trait` in their name that are subclasses of [OBA:0000001 biological attribute](https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBA_0000001&lang=en&viewMode=All&siblings=false) using this snippet:
 
```SPARQL
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX obo: <http://purl.obolibrary.org/obo_>
PREFIX OBA: <http://purl.obolibrary.org/obo/OBA_>
PREFIX subClassOf: <http://www.w3.org/2000/01/rdf-schema#subClassOf>
PREFIX label: <http://www.w3.org/2000/01/rdf-schema#label>

######################################
## OBA:0000001 biological attribute
## https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBA_0000001&lang=en&viewMode=All&siblings=false
######################################
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
########################
### chain ROBOT commands
########################
# THIS IS THE COMMAND TO USE:
# robot reason --reasoner ELK --input ~/bio-attribute-ontology/src/ontology/oba-edit.obo query --use-graphs true --queries oba_traitsQ2.rq --output-dir ~/tmp/results/ --format tsv
########################
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

SELECT DISTINCT
(IRI(?cls) AS ?CLASS)
(STR(?label) AS ?LABEL)
WHERE {
  VALUES ?query_strings { "trait" }
# VALUES ?query_strings { "trait" "attribute" }
# 'subClassOf:+' A path of one or more occurrences of 'subClassOf'
#### see SPARQL 1.1 Property Paths https://www.w3.org/TR/sparql11-property-paths/
      ?cls subClassOf:+ OBA:0000001 ; # biological attribute
           label: ?label.
  FILTER ( CONTAINS(LCASE(STR(?label)), ?query_strings))
      }
```
2. The total number of terms in OBA with `trait` in their name is *1853*.
```sh
robot reason --reasoner ELK --input ~/bio-attribute-ontology/src/ontology/oba-edit.obo export --header "ID|LABEL" --include "classes" --export ~/tmp/oba-edit_terms_2022-11-10.tsv
grep -i -c trait oba-edit_terms_2022-11-10.tsv
1853
```
3. There are `1853 - 1640 = 213` *trait*-labelled terms in OBA that are not subclasses of [OBA:0000001 biological attribute](https://www.ebi.ac.uk/ols/ontologies/oba/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBA_0000001&lang=en&viewMode=All&siblings=false)

**Comment by matentzn** [comment]
This has been finished: https://www.ebi.ac.uk/ols4/ontologies/oba
