### ISSUE TITLE
add synonyms

### ISSUE THREAD

**Issue by megbalk** [obophenotype/bio-attribute-ontology#89]
there are a few terms I'd like to make synonyms for:
forelimb length: exact: forearm length, related: ulna length
chest circumference: exact: chest girth or girth of chest
skin mass: broad: body mass

**Comment by matentzn** [comment]
what is the advantage of broad and narrow synonyms in this case? Isnt it better if these are exct synonyms of the correct term?

**Comment by megbalk** [comment]
I was thinking if someone was searching "body mass" they would get "skin mass" too as an option. Maybe I am misunderstanding broad synonyms?

**Comment by matentzn** [comment]
I think on a second thought, we can add these if you think a user may be typing the one while looking for the other..

**Comment by megbalk** [comment]
We decided to only do chest girth as a synonym since one can get to the other synonyms using the ontology, but "girth" does not currently exist in the ontology.

**Comment by megbalk** [comment]
@matentzn do I need to re-run making a synonym on the synonym-pipeline branch?

**Comment by matentzn** [comment]
I think that pull request was merged. After you edited the tables, run the pipeline locally and create a PR! Let me know if you have trouble figuring out what to do.
