### ISSUE TITLE
standardizing "size trait"

### ISSUE THREAD

**Issue by megbalk** [obophenotype/bio-attribute-ontology#90]
I'd like to standardize the following terms to say "X size trait":

ulna size -> ulna size trait
fibula size -> fibula size trait
radius bone size -> radius size trait
pelvic girdle bone/zone size -> pelvic girdle size trait
patella size -> patella size trait
calcaneus size ->  calcaneus size trait

**Comment by matentzn** [comment]
I am wondering now if we should rather remove the word "trait" from all the labels. I think most users really do not care much about that distinction, and I think it introduces a lot of fluff everywhere. What do you think @megbalk @dosumis @rays22 @cmungall

**Comment by megbalk** [comment]
I agree that the word "trait" is probably not needed. I also think we should not use "bone", because I'm sure there are non-bone traits.

**Comment by matentzn** [comment]
We should use "bone" only when the trait is literally a bone trait, not otherwise!

**Comment by megbalk** [comment]
@matentzn am I good to do the following:
standardize to "structure trait" (e.g., ulna trait) with subclass "structure bone size" (e.g., ulna bone size)?

**Comment by matentzn** [comment]
I think yes, but best make a few changes at first, and we will go over them with @dosumis and @rays22 in the next call just to be sure.

**Comment by megbalk** [comment]
ok! I've been having issues making changes in OBA using protégé, where my changes do not show up on GitHub. Have you had any issues? @rays22 has been helping me, but I want to know how pervasive this is.

**Comment by matentzn** [comment]
Hm, most of the changes to OBA should be done in the TSV files, rarely in protege. So if you look at you GitHub desktop, you see no changed files?

**Comment by megbalk** [comment]
Exactly. @rays22 and I did some testing. Unless I save as another file, I don't see changes. Ray also suggested I try editing in a text editor and then saving it. I still need to test that.
